export interface SelectOption {
  value: string;
  label: string;
}

export interface GeographicData {
  provincias: SelectOption[];
  departamentosPorProvincia: { [key: string]: SelectOption[] };
  ciudadesPorProvincia: { [key: string]: SelectOption[] };
}

export const provinciaOptions: SelectOption[] = [
  { value: 'buenos_aires', label: 'Buenos Aires' },
  { value: 'catamarca', label: 'Catamarca' },
  { value: 'chaco', label: 'Chaco' },
  { value: 'chubut', label: 'Chubut' },
  { value: 'cordoba', label: 'Córdoba' },
  { value: 'corrientes', label: 'Corrientes' },
  { value: 'entre_rios', label: 'Entre Ríos' },
  { value: 'formosa', label: 'Formosa' },
  { value: 'jujuy', label: 'Jujuy' },
  { value: 'la_pampa', label: 'La Pampa' },
  { value: 'la_rioja', label: 'La Rioja' },
  { value: 'mendoza', label: 'Mendoza' },
  { value: 'misiones', label: 'Misiones' },
  { value: 'neuquen', label: 'Neuquén' },
  { value: 'rio_negro', label: 'Río Negro' },
  { value: 'salta', label: 'Salta' },
  { value: 'san_juan', label: 'San Juan' },
  { value: 'san_luis', label: 'San Luis' },
  { value: 'santa_cruz', label: 'Santa Cruz' },
  { value: 'santa_fe', label: 'Santa Fe' },
  { value: 'santiago_del_estero', label: 'Santiago del Estero' },
  { value: 'tierra_del_fuego', label: 'Tierra del Fuego' },
  { value: 'tucuman', label: 'Tucumán' },
  { value: 'caba', label: 'Ciudad Autónoma de Buenos Aires' }
];

export const departamentosPorProvincia: { [key: string]: SelectOption[] } = {
  'buenos_aires': [
    { value: 'adolfo_alsina', label: 'Adolfo Alsina' },
    { value: 'adolfo_gonzales_chaves', label: 'Adolfo Gonzales Chaves' },
    { value: 'alberti', label: 'Alberti' },
    { value: 'almirante_brown', label: 'Almirante Brown' },
    { value: 'arrecifes', label: 'Arrecifes' },
    { value: 'avellaneda', label: 'Avellaneda' },
    { value: 'ayacucho', label: 'Ayacucho' },
    { value: 'azul', label: 'Azul' },
    { value: 'bahia_blanca', label: 'Bahía Blanca' },
    { value: 'balcarce', label: 'Balcarce' },
    { value: 'baradero', label: 'Baradero' },
    { value: 'benito_juarez', label: 'Benito Juárez' },
    { value: 'berazategui', label: 'Berazategui' },
    { value: 'berisso', label: 'Berisso' },
    { value: 'bolivar', label: 'Bolívar' },
    { value: 'bragado', label: 'Bragado' },
    { value: 'brandsen', label: 'Brandsen' },
    { value: 'campana', label: 'Campana' },
    { value: 'canuelas', label: 'Cañuelas' },
    { value: 'capitan_sarmiento', label: 'Capitán Sarmiento' },
    { value: 'carlos_casares', label: 'Carlos Casares' },
    { value: 'carlos_tejedor', label: 'Carlos Tejedor' },
    { value: 'carmen_de_areco', label: 'Carmen de Areco' },
    { value: 'castelli', label: 'Castelli' },
    { value: 'chascomus', label: 'Chascomús' },
    { value: 'chivilcoy', label: 'Chivilcoy' },
    { value: 'colon', label: 'Colón' },
    { value: 'coronel_dorrego', label: 'Coronel Dorrego' },
    { value: 'coronel_pringles', label: 'Coronel Pringles' },
    { value: 'coronel_rosales', label: 'Coronel Rosales' },
    { value: 'coronel_suarez', label: 'Coronel Suárez' },
    { value: 'daireaux', label: 'Daireaux' },
    { value: 'dolores', label: 'Dolores' },
    { value: 'ensenada', label: 'Ensenada' },
    { value: 'escobar', label: 'Escobar' },
    { value: 'esteban_echeverria', label: 'Esteban Echeverría' },
    { value: 'exaltacion_de_la_cruz', label: 'Exaltación de la Cruz' },
    { value: 'ezeiza', label: 'Ezeiza' },
    { value: 'florencio_varela', label: 'Florencio Varela' },
    { value: 'general_alvarado', label: 'General Alvarado' },
    { value: 'general_alvear', label: 'General Alvear' },
    { value: 'general_arenales', label: 'General Arenales' },
    { value: 'general_belgrano', label: 'General Belgrano' },
    { value: 'general_guido', label: 'General Guido' },
    { value: 'general_la_madrid', label: 'General La Madrid' },
    { value: 'general_las_heras', label: 'General Las Heras' },
    { value: 'general_lavalle', label: 'General Lavalle' },
    { value: 'general_madariaga', label: 'General Madariaga' },
    { value: 'general_paz', label: 'General Paz' },
    { value: 'general_pinto', label: 'General Pinto' },
    { value: 'general_pueyrredon', label: 'General Pueyrredón' },
    { value: 'general_rodriguez', label: 'General Rodríguez' },
    { value: 'general_san_martin', label: 'General San Martín' },
    { value: 'general_viamonte', label: 'General Viamonte' },
    { value: 'general_villegas', label: 'General Villegas' },
    { value: 'guamini', label: 'Guaminí' },
    { value: 'hipolito_yrigoyen', label: 'Hipólito Yrigoyen' },
    { value: 'hurlingham', label: 'Hurlingham' },
    { value: 'ituzaingo', label: 'Ituzaingó' },
    { value: 'jose_c_paz', label: 'José C. Paz' },
    { value: 'junin', label: 'Junín' },
    { value: 'la_costa', label: 'La Costa' },
    { value: 'la_matanza', label: 'La Matanza' },
    { value: 'la_plata', label: 'La Plata' },
    { value: 'lanus', label: 'Lanús' },
    { value: 'laprida', label: 'Laprida' },
    { value: 'las_flores', label: 'Las Flores' },
    { value: 'leandro_n_alem', label: 'Leandro N. Alem' },
    { value: 'lincoln', label: 'Lincoln' },
    { value: 'loberia', label: 'Lobería' },
    { value: 'lobos', label: 'Lobos' },
    { value: 'lomas_de_zamora', label: 'Lomas de Zamora' },
    { value: 'lujan', label: 'Luján' },
    { value: 'magdalena', label: 'Magdalena' },
    { value: 'maipu', label: 'Maipú' },
    { value: 'malvinas_argentinas', label: 'Malvinas Argentinas' },
    { value: 'mar_chiquita', label: 'Mar Chiquita' },
    { value: 'marcos_paz', label: 'Marcos Paz' },
    { value: 'mercedes', label: 'Mercedes' },
    { value: 'merlo', label: 'Merlo' },
    { value: 'monte', label: 'Monte' },
    { value: 'monte_hermoso', label: 'Monte Hermoso' },
    { value: 'moreno', label: 'Moreno' },
    { value: 'moron', label: 'Morón' },
    { value: 'navarro', label: 'Navarro' },
    { value: 'necochea', label: 'Necochea' },
    { value: 'nueve_de_julio', label: 'Nueve de Julio' },
    { value: 'olavarria', label: 'Olavarría' },
    { value: 'patagones', label: 'Patagones' },
    { value: 'pehuajo', label: 'Pehuajó' },
    { value: 'pellegrini', label: 'Pellegrini' },
    { value: 'pergamino', label: 'Pergamino' },
    { value: 'pila', label: 'Pila' },
    { value: 'pilar', label: 'Pilar' },
    { value: 'pinamar', label: 'Pinamar' },
    { value: 'presidente_peron', label: 'Presidente Perón' },
    { value: 'puán', label: 'Puán' },
    { value: 'punta_indio', label: 'Punta Indio' },
    { value: 'quilmes', label: 'Quilmes' },
    { value: 'ramallo', label: 'Ramallo' },
    { value: 'rauch', label: 'Rauch' },
    { value: 'rivadavia', label: 'Rivadavia' },
    { value: 'rojas', label: 'Rojas' },
    { value: 'roque_perez', label: 'Roque Pérez' },
    { value: 'saavedra', label: 'Saavedra' },
    { value: 'saladillo', label: 'Saladillo' },
    { value: 'salliqueló', label: 'Salliqueló' },
    { value: 'salto', label: 'Salto' },
    { value: 'san_andres_de_giles', label: 'San Andrés de Giles' },
    { value: 'san_antonio_de_areco', label: 'San Antonio de Areco' },
    { value: 'san_cayetano', label: 'San Cayetano' },
    { value: 'san_fernando', label: 'San Fernando' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'san_nicolas', label: 'San Nicolás' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'san_vicente', label: 'San Vicente' },
    { value: 'suipacha', label: 'Suipacha' },
    { value: 'tandil', label: 'Tandil' },
    { value: 'tapalque', label: 'Tapalqué' },
    { value: 'tigre', label: 'Tigre' },
    { value: 'tordillo', label: 'Tordillo' },
    { value: 'tornquist', label: 'Tornquist' },
    { value: 'trenque_lauquen', label: 'Trenque Lauquen' },
    { value: 'tres_arroyos', label: 'Tres Arroyos' },
    { value: 'tres_de_febrero', label: 'Tres de Febrero' },
    { value: 'tres_lomas', label: 'Tres Lomas' },
    { value: 'veinticinco_de_mayo', label: 'Veinticinco de Mayo' },
    { value: 'vicente_lopez', label: 'Vicente López' },
    { value: 'villa_gesell', label: 'Villa Gesell' },
    { value: 'villarino', label: 'Villarino' },
    { value: 'zarate', label: 'Zárate' }
  ],
  'catamarca': [
    { value: 'ambato', label: 'Ambato' },
    { value: 'ancasti', label: 'Ancasti' },
    { value: 'andalgala', label: 'Andalgalá' },
    { value: 'antofagasta_de_la_sierra', label: 'Antofagasta de la Sierra' },
    { value: 'belen', label: 'Belén' },
    { value: 'capayan', label: 'Capayán' },
    { value: 'capital', label: 'Capital' },
    { value: 'el_alto', label: 'El Alto' },
    { value: 'fray_mamerto_esquiu', label: 'Fray Mamerto Esquiú' },
    { value: 'la_paz', label: 'La Paz' },
    { value: 'paclin', label: 'Paclín' },
    { value: 'poman', label: 'Pomán' },
    { value: 'santa_maria', label: 'Santa María' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'tinogasta', label: 'Tinogasta' },
    { value: 'valle_viejo', label: 'Valle Viejo' }
  ],
  'chaco': [
    { value: 'almirante_brown', label: 'Almirante Brown' },
    { value: 'bermejo', label: 'Bermejo' },
    { value: 'chacabuco', label: 'Chacabuco' },
    { value: 'comandante_fernandez', label: 'Comandante Fernández' },
    { value: 'dos_de_mayo', label: 'Dos de Mayo' },
    { value: 'fray_justo_santa_maria_de_oro', label: 'Fray Justo Santa María de Oro' },
    { value: 'general_belgrano', label: 'General Belgrano' },
    { value: 'general_donovan', label: 'General Donovan' },
    { value: 'general_güemes', label: 'General Güemes' },
    { value: 'independencia', label: 'Independencia' },
    { value: 'libertad', label: 'Libertad' },
    { value: 'libertador_general_san_martin', label: 'Libertador General San Martín' },
    { value: 'maipu', label: 'Maipú' },
    { value: 'mayor_luis_j_fontana', label: 'Mayor Luis J. Fontana' },
    { value: 'nueve_de_julio', label: 'Nueve de Julio' },
    { value: 'o_higgins', label: 'O\'Higgins' },
    { value: 'presidencia_de_la_plaza', label: 'Presidencia de la Plaza' },
    { value: 'primero_de_mayo', label: 'Primero de Mayo' },
    { value: 'quitilipi', label: 'Quitilipi' },
    { value: 'san_fernando', label: 'San Fernando' },
    { value: 'san_lorenzo', label: 'San Lorenzo' },
    { value: 'sargento_cabral', label: 'Sargento Cabral' },
    { value: 'tapenaga', label: 'Tapenagá' },
    { value: 'veinticinco_de_mayo', label: 'Veinticinco de Mayo' }
  ],
  'chubut': [
    { value: 'biedma', label: 'Biedma' },
    { value: 'cushamen', label: 'Cushamen' },
    { value: 'escalante', label: 'Escalante' },
    { value: 'florentino_ameghino', label: 'Florentino Ameghino' },
    { value: 'futaleufu', label: 'Futaleufú' },
    { value: 'gaiman', label: 'Gaiman' },
    { value: 'gastre', label: 'Gastre' },
    { value: 'languiñeo', label: 'Languiñeo' },
    { value: 'martires', label: 'Mártires' },
    { value: 'paso_de_indios', label: 'Paso de Indios' },
    { value: 'rawson', label: 'Rawson' },
    { value: 'rio_senguer', label: 'Río Senguer' },
    { value: 'sarmiento', label: 'Sarmiento' },
    { value: 'tehuelches', label: 'Tehuelches' },
    { value: 'telsen', label: 'Telsen' }
  ],
  'cordoba': [
    { value: 'calamuchita', label: 'Calamuchita' },
    { value: 'capital', label: 'Capital' },
    { value: 'colon', label: 'Colón' },
    { value: 'cruz_del_eje', label: 'Cruz del Eje' },
    { value: 'general_roca', label: 'General Roca' },
    { value: 'general_san_martin', label: 'General San Martín' },
    { value: 'ischilín', label: 'Ischilin' },
    { value: 'juarez_celman', label: 'Juárez Celman' },
    { value: 'marcos_juarez', label: 'Marcos Juárez' },
    { value: 'minas', label: 'Minas' },
    { value: 'pocho', label: 'Pocho' },
    { value: 'presidente_roque_saenz_peña', label: 'Presidente Roque Sáenz Peña' },
    { value: 'punilla', label: 'Punilla' },
    { value: 'rio_cuarto', label: 'Río Cuarto' },
    { value: 'rio_primero', label: 'Río Primero' },
    { value: 'rio_seco', label: 'Río Seco' },
    { value: 'rio_segundo', label: 'Río Segundo' },
    { value: 'san_alberto', label: 'San Alberto' },
    { value: 'san_javier', label: 'San Javier' },
    { value: 'san_justo', label: 'San Justo' },
    { value: 'santa_maria', label: 'Santa María' },
    { value: 'sobremonte', label: 'Sobremonte' },
    { value: 'tercero_arriba', label: 'Tercero Arriba' },
    { value: 'totoral', label: 'Totoral' },
    { value: 'tulumba', label: 'Tulumba' },
    { value: 'union', label: 'Unión' }
  ],
  'corrientes': [
    { value: 'bella_vista', label: 'Bella Vista' },
    { value: 'beron_de_astrada', label: 'Berón de Astrada' },
    { value: 'capital', label: 'Capital' },
    { value: 'concepcion', label: 'Concepción' },
    { value: 'curuzu_cuatia', label: 'Curuzú Cuatiá' },
    { value: 'empedrado', label: 'Empedrado' },
    { value: 'esquina', label: 'Esquina' },
    { value: 'general_alvear', label: 'General Alvear' },
    { value: 'general_paz', label: 'General Paz' },
    { value: 'goya', label: 'Goya' },
    { value: 'itatí', label: 'Itatí' },
    { value: 'ituzaingo', label: 'Ituzaingó' },
    { value: 'lavalle', label: 'Lavalle' },
    { value: 'mburucuya', label: 'Mburucuyá' },
    { value: 'mercedes', label: 'Mercedes' },
    { value: 'monte_caseros', label: 'Monte Caseros' },
    { value: 'paso_de_los_libres', label: 'Paso de los Libres' },
    { value: 'saladas', label: 'Saladas' },
    { value: 'san_cosme', label: 'San Cosme' },
    { value: 'san_luis_del_palmar', label: 'San Luis del Palmar' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'san_miguel', label: 'San Miguel' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'santo_tome', label: 'Santo Tomé' },
    { value: 'sauce', label: 'Sauce' }
  ],
  'entre_rios': [
    { value: 'colon', label: 'Colón' },
    { value: 'concordia', label: 'Concordia' },
    { value: 'diamante', label: 'Diamante' },
    { value: 'federacion', label: 'Federación' },
    { value: 'federo', label: 'Federó' },
    { value: 'feliciano', label: 'Feliciano' },
    { value: 'gualeguay', label: 'Gualeguay' },
    { value: 'gualeguaychu', label: 'Gualeguaychú' },
    { value: 'islas_del_ibicuy', label: 'Islas del Ibicuy' },
    { value: 'la_paz', label: 'La Paz' },
    { value: 'nogoya', label: 'Nogoyá' },
    { value: 'parana', label: 'Paraná' },
    { value: 'san_salvador', label: 'San Salvador' },
    { value: 'tala', label: 'Tala' },
    { value: 'uruguay', label: 'Uruguay' },
    { value: 'victoria', label: 'Victoria' },
    { value: 'villaguay', label: 'Villaguay' }
  ],
  'formosa': [
    { value: 'bermejo', label: 'Bermejo' },
    { value: 'formosa', label: 'Formosa' },
    { value: 'laishi', label: 'Laishí' },
    { value: 'matacos', label: 'Matacos' },
    { value: 'patino', label: 'Patiño' },
    { value: 'pilagas', label: 'Pilagás' },
    { value: 'pilcomayo', label: 'Pilcomayo' },
    { value: 'ramón_lista', label: 'Ramón Lista' },
    { value: 'pirané', label: 'Pirané' }
  ],
  'jujuy': [
    { value: 'cochinoca', label: 'Cochinoca' },
    { value: 'dr_manuel_belgrano', label: 'Dr. Manuel Belgrano' },
    { value: 'el_carmen', label: 'El Carmen' },
    { value: 'humahuaca', label: 'Humahuaca' },
    { value: 'ledesma', label: 'Ledesma' },
    { value: 'palpalá', label: 'Palpalá' },
    { value: 'rinconada', label: 'Rinconada' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'santa_barbara', label: 'Santa Bárbara' },
    { value: 'susques', label: 'Susques' },
    { value: 'tilcara', label: 'Tilcara' },
    { value: 'tumbaya', label: 'Tumbaya' },
    { value: 'valle_grande', label: 'Valle Grande' },
    { value: 'yavi', label: 'Yavi' }
  ],
  'la_pampa': [
    { value: 'atreuco', label: 'Atreucó' },
    { value: 'caleu_caleu', label: 'Caleu Caleu' },
    { value: 'capital', label: 'Capital' },
    { value: 'catrilo', label: 'Catriló' },
    { value: 'chalileo', label: 'Chalileo' },
    { value: 'chapaleufu', label: 'Chapaleufú' },
    { value: 'conhelo', label: 'Conhelo' },
    { value: 'curaco', label: 'Curacó' },
    { value: 'guatrache', label: 'Guatraché' },
    { value: 'hucal', label: 'Hucal' },
    { value: 'lihuel_calel', label: 'Lihuel Calel' },
    { value: 'limay_mahuida', label: 'Limay Mahuida' },
    { value: 'loventue', label: 'Loventué' },
    { value: 'maraco', label: 'Maracó' },
    { value: 'puelen', label: 'Puelén' },
    { value: 'quemu_quemu', label: 'Quemú Quemú' },
    { value: 'rancul', label: 'Rancul' },
    { value: 'realico', label: 'Realicó' },
    { value: 'toay', label: 'Toay' },
    { value: 'trenel', label: 'Trenel' },
    { value: 'utracan', label: 'Utracán' }
  ],
  'la_rioja': [
    { value: 'angel_vicente_peñaloza', label: 'Ángel Vicente Peñaloza' },
    { value: 'arauco', label: 'Arauco' },
    { value: 'capital', label: 'Capital' },
    { value: 'castro_barros', label: 'Castro Barros' },
    { value: 'chamical', label: 'Chamical' },
    { value: 'chilecito', label: 'Chilecito' },
    { value: 'coronel_felipe_varela', label: 'Coronel Felipe Varela' },
    { value: 'famatina', label: 'Famatina' },
    { value: 'general_belgrano', label: 'General Belgrano' },
    { value: 'general_juan_facundo_quiroga', label: 'General Juan Facundo Quiroga' },
    { value: 'general_lamadrid', label: 'General Lamadrid' },
    { value: 'general_ocampo', label: 'General Ocampo' },
    { value: 'general_san_martin', label: 'General San Martín' },
    { value: 'independencia', label: 'Independencia' },
    { value: 'rosario_vera_peñaloza', label: 'Rosario Vera Peñaloza' },
    { value: 'san_blas_de_los_sauces', label: 'San Blas de los Sauces' },
    { value: 'sanagasta', label: 'Sanagasta' },
    { value: 'vinchina', label: 'Vinchina' }
  ],
  'mendoza': [
    { value: 'capital', label: 'Capital' },
    { value: 'general_alvear', label: 'General Alvear' },
    { value: 'godoy_cruz', label: 'Godoy Cruz' },
    { value: 'guaymallen', label: 'Guaymallén' },
    { value: 'junin', label: 'Junín' },
    { value: 'la_paz', label: 'La Paz' },
    { value: 'las_heras', label: 'Las Heras' },
    { value: 'lavalle', label: 'Lavalle' },
    { value: 'lujan_de_cuyo', label: 'Luján de Cuyo' },
    { value: 'maipu', label: 'Maipú' },
    { value: 'malargue', label: 'Malargüe' },
    { value: 'rivadavia', label: 'Rivadavia' },
    { value: 'san_carlos', label: 'San Carlos' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'san_rafael', label: 'San Rafael' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'tunuyan', label: 'Tunuyán' },
    { value: 'tupungato', label: 'Tupungato' }
  ],
  'misiones': [
    { value: 'apostoles', label: 'Apóstoles' },
    { value: 'cainguas', label: 'Cainguás' },
    { value: 'candelaria', label: 'Candelaria' },
    { value: 'capital', label: 'Capital' },
    { value: 'concepcion', label: 'Concepción' },
    { value: 'eldorado', label: 'Eldorado' },
    { value: 'general_manuel_belgrano', label: 'General Manuel Belgrano' },
    { value: 'guarani', label: 'Guaraní' },
    { value: 'iguazu', label: 'Iguazú' },
    { value: 'leandro_n_alem', label: 'Leandro N. Alem' },
    { value: 'libertador_general_san_martin', label: 'Libertador General San Martín' },
    { value: 'montecarlo', label: 'Montecarlo' },
    { value: 'obera', label: 'Oberá' },
    { value: 'san_ignacio', label: 'San Ignacio' },
    { value: 'san_javier', label: 'San Javier' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'san_pedro', label: 'San Pedro' }
  ],
  'neuquen': [
    { value: 'alumine', label: 'Aluminé' },
    { value: 'añelo', label: 'Añelo' },
    { value: 'catán_lil', label: 'Catán Lil' },
    { value: 'chos_malal', label: 'Chos Malal' },
    { value: 'collon_cura', label: 'Collón Curá' },
    { value: 'confluencia', label: 'Confluencia' },
    { value: 'huiliches', label: 'Huiliches' },
    { value: 'lacar', label: 'Lácar' },
    { value: 'loncopue', label: 'Loncopué' },
    { value: 'los_lagos', label: 'Los Lagos' },
    { value: 'minas', label: 'Minas' },
    { value: 'ñorquin', label: 'Ñorquín' },
    { value: 'pehuenches', label: 'Pehuenches' },
    { value: 'picun_leufu', label: 'Picún Leufú' },
    { value: 'picunches', label: 'Picunches' },
    { value: 'zapala', label: 'Zapala' }
  ],
  'rio_negro': [
    { value: 'adolfo_alsina', label: 'Adolfo Alsina' },
    { value: 'avellaneda', label: 'Avellaneda' },
    { value: 'bariloche', label: 'Bariloche' },
    { value: 'conesa', label: 'Conesa' },
    { value: 'el_cuy', label: 'El Cuy' },
    { value: 'general_roca', label: 'General Roca' },
    { value: 'ñorquinco', label: 'Ñorquinco' },
    { value: 'nueve_de_julio', label: 'Nueve de Julio' },
    { value: 'pico', label: 'Pico' },
    { value: 'pilcaniyeu', label: 'Pilcaniyeu' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'valcheta', label: 'Valcheta' },
    { value: 'viedma', label: 'Viedma' }
  ],
  'salta': [
    { value: 'anta', label: 'Anta' },
    { value: 'cachi', label: 'Cachi' },
    { value: 'cafayate', label: 'Cafayate' },
    { value: 'capital', label: 'Capital' },
    { value: 'cerrillos', label: 'Cerrillos' },
    { value: 'chicoana', label: 'Chicoana' },
    { value: 'general_guemes', label: 'General Güemes' },
    { value: 'general_jose_de_san_martin', label: 'General José de San Martín' },
    { value: 'guachipas', label: 'Guachipas' },
    { value: 'iruya', label: 'Iruya' },
    { value: 'la_caldera', label: 'La Caldera' },
    { value: 'la_candelaria', label: 'La Candelaria' },
    { value: 'la_poma', label: 'La Poma' },
    { value: 'la_viña', label: 'La Viña' },
    { value: 'los_andes', label: 'Los Andes' },
    { value: 'metan', label: 'Metán' },
    { value: 'molinos', label: 'Molinos' },
    { value: 'oran', label: 'Orán' },
    { value: 'rivadavia', label: 'Rivadavia' },
    { value: 'rosario_de_lerma', label: 'Rosario de Lerma' },
    { value: 'rosario_de_la_frontera', label: 'Rosario de la Frontera' },
    { value: 'san_carlos', label: 'San Carlos' },
    { value: 'santa_victoria', label: 'Santa Victoria' }
  ],
  'san_juan': [
    { value: '25_de_mayo', label: '25 de Mayo' },
    { value: 'albardon', label: 'Albardón' },
    { value: 'angaco', label: 'Angaco' },
    { value: 'calingasta', label: 'Calingasta' },
    { value: 'capital', label: 'Capital' },
    { value: 'caucete', label: 'Caucete' },
    { value: 'chimbas', label: 'Chimbas' },
    { value: 'iglesia', label: 'Iglesia' },
    { value: 'jachal', label: 'Jáchal' },
    { value: 'pocito', label: 'Pocito' },
    { value: 'rawson', label: 'Rawson' },
    { value: 'rivadavia', label: 'Rivadavia' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'santa_lucia', label: 'Santa Lucía' },
    { value: 'sarmiento', label: 'Sarmiento' },
    { value: 'ullum', label: 'Ullum' },
    { value: 'valle_fertil', label: 'Valle Fértil' },
    { value: 'zonda', label: 'Zonda' }
  ],
  'san_luis': [
    { value: 'ayacucho', label: 'Ayacucho' },
    { value: 'belgrano', label: 'Belgrano' },
    { value: 'capital', label: 'Capital' },
    { value: 'chacabuco', label: 'Chacabuco' },
    { value: 'coronel_pringles', label: 'Coronel Pringles' },
    { value: 'dupuy', label: 'Dupuy' },
    { value: 'general_pedernera', label: 'General Pedernera' },
    { value: 'gobernador_dupuy', label: 'Gobernador Dupuy' },
    { value: 'junin', label: 'Junín' },
    { value: 'la_capital', label: 'La Capital' },
    { value: 'libertador_general_san_martin', label: 'Libertador General San Martín' }
  ],
  'santa_cruz': [
    { value: 'corpen_aike', label: 'Corpen Aike' },
    { value: 'deseado', label: 'Deseado' },
    { value: 'guer_aike', label: 'Güer Aike' },
    { value: 'lago_argentino', label: 'Lago Argentino' },
    { value: 'lago_buenos_aires', label: 'Lago Buenos Aires' },
    { value: 'magallanes', label: 'Magallanes' },
    { value: 'rio_chico', label: 'Río Chico' }
  ],
  'santa_fe': [
    { value: 'belgrano', label: 'Belgrano' },
    { value: 'caseros', label: 'Caseros' },
    { value: 'castellanos', label: 'Castellanos' },
    { value: 'constitucion', label: 'Constitución' },
    { value: 'garay', label: 'Garay' },
    { value: 'general_lopez', label: 'General López' },
    { value: 'general_obligado', label: 'General Obligado' },
    { value: 'iriondo', label: 'Iriondo' },
    { value: 'la_capital', label: 'La Capital' },
    { value: 'las_colonias', label: 'Las Colonias' },
    { value: 'nueve_de_julio', label: 'Nueve de Julio' },
    { value: 'rosario', label: 'Rosario' },
    { value: 'san_cristobal', label: 'San Cristóbal' },
    { value: 'san_javier', label: 'San Javier' },
    { value: 'san_jeronimo', label: 'San Jerónimo' },
    { value: 'san_justo', label: 'San Justo' },
    { value: 'san_lorenzo', label: 'San Lorenzo' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'vera', label: 'Vera' }
  ],
  'santiago_del_estero': [
    { value: 'aguirre', label: 'Aguirre' },
    { value: 'alberdi', label: 'Alberdi' },
    { value: 'atamisqui', label: 'Atamisqui' },
    { value: 'avellaneda', label: 'Avellaneda' },
    { value: 'banda', label: 'Banda' },
    { value: 'belgrano', label: 'Belgrano' },
    { value: 'capital', label: 'Capital' },
    { value: 'caseros', label: 'Caseros' },
    { value: 'choya', label: 'Choya' },
    { value: 'copo', label: 'Copo' },
    { value: 'figueroa', label: 'Figueroa' },
    { value: 'general_taboada', label: 'General Taboada' },
    { value: 'guasayan', label: 'Guasayán' },
    { value: 'ibarra', label: 'Ibarra' },
    { value: 'jimenez', label: 'Jiménez' },
    { value: 'juan_felipe_ibarra', label: 'Juan Felipe Ibarra' },
    { value: 'loreto', label: 'Loreto' },
    { value: 'mitre', label: 'Mitre' },
    { value: 'moreno', label: 'Moreno' },
    { value: 'ojo_de_agua', label: 'Ojo de Agua' },
    { value: 'pellegrini', label: 'Pellegrini' },
    { value: 'quebrachos', label: 'Quebrachos' },
    { value: 'rio_hondo', label: 'Río Hondo' },
    { value: 'rivadavia', label: 'Rivadavia' },
    { value: 'robles', label: 'Robles' },
    { value: 'salavina', label: 'Salavina' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'sarmiento', label: 'Sarmiento' },
    { value: 'silipica', label: 'Silípica' }
  ],
  'tierra_del_fuego': [
    { value: 'rio_grande', label: 'Río Grande' },
    { value: 'ushuaia', label: 'Ushuaia' }
  ],
  'tucuman': [
    { value: 'burruyacu', label: 'Burruyacú' },
    { value: 'capital', label: 'Capital' },
    { value: 'chicligasta', label: 'Chicligasta' },
    { value: 'cruz_alta', label: 'Cruz Alta' },
    { value: 'famailla', label: 'Famaillá' },
    { value: 'graneros', label: 'Graneros' },
    { value: 'juan_bautista_alberdi', label: 'Juan Bautista Alberdi' },
    { value: 'la_cocha', label: 'La Cocha' },
    { value: 'leales', label: 'Leales' },
    { value: 'lules', label: 'Lules' },
    { value: 'monteros', label: 'Monteros' },
    { value: 'rio_chico', label: 'Río Chico' },
    { value: 'simoca', label: 'Simoca' },
    { value: 'tafi_del_valle', label: 'Tafí del Valle' },
    { value: 'tafi_viejo', label: 'Tafí Viejo' },
    { value: 'trancas', label: 'Trancas' },
    { value: 'yerba_buena', label: 'Yerba Buena' }
  ],
  'caba': [
    { value: 'comuna_1', label: 'Comuna 1 (Retiro, San Nicolás, Puerto Madero, San Telmo, Montserrat, Constitución)' },
    { value: 'comuna_2', label: 'Comuna 2 (Recoleta)' },
    { value: 'comuna_3', label: 'Comuna 3 (Balvanera, San Cristóbal)' },
    { value: 'comuna_4', label: 'Comuna 4 (La Boca, Barracas, Parque Patricios, Nueva Pompeya)' },
    { value: 'comuna_5', label: 'Comuna 5 (Boedo, Almagro)' },
    { value: 'comuna_6', label: 'Comuna 6 (Caballito)' },
    { value: 'comuna_7', label: 'Comuna 7 (Flores, Parque Chacabuco)' },
    { value: 'comuna_8', label: 'Comuna 8 (Villa Soldati, Villa Riachuelo, Villa Lugano)' },
    { value: 'comuna_9', label: 'Comuna 9 (Liniers, Mataderos, Parque Avellaneda)' },
    { value: 'comuna_10', label: 'Comuna 10 (Villa Real, Monte Castro, Versalles, Floresta, Vélez Sársfield, Villa Luro)' },
    { value: 'comuna_11', label: 'Comuna 11 (Villa General Mitre, Villa Devoto, Villa del Pino, Villa Santa Rita)' },
    { value: 'comuna_12', label: 'Comuna 12 (Coghlan, Saavedra, Villa Urquiza, Villa Pueyrredón)' },
    { value: 'comuna_13', label: 'Comuna 13 (Núñez, Belgrano, Colegiales)' },
    { value: 'comuna_14', label: 'Comuna 14 (Palermo)' },
    { value: 'comuna_15', label: 'Comuna 15 (Chacarita, Villa Crespo, La Paternal, Villa Ortúzar, Agronomía, Parque Chas)' }
  ]
};

export const ciudadesPorProvincia: { [key: string]: SelectOption[] } = {
  'buenos_aires': [
    { value: 'la_plata', label: 'La Plata' },
    { value: 'mar_del_plata', label: 'Mar del Plata' },
    { value: 'bahia_blanca', label: 'Bahía Blanca' },
    { value: 'tandil', label: 'Tandil' },
    { value: 'olavarria', label: 'Olavarría' },
    { value: 'junin', label: 'Junín' },
    { value: 'san_nicolas', label: 'San Nicolás' },
    { value: 'zarate', label: 'Zárate' },
    { value: 'quilmes', label: 'Quilmes' },
    { value: 'lanus', label: 'Lanús' },
    { value: 'moron', label: 'Morón' },
    { value: 'san_isidro', label: 'San Isidro' },
    { value: 'tigre', label: 'Tigre' },
    { value: 'pergamino', label: 'Pergamino' },
    { value: 'azul', label: 'Azul' },
    { value: 'mercedes', label: 'Mercedes' },
    { value: 'lujan', label: 'Luján' },
    { value: 'berisso', label: 'Berisso' },
    { value: 'ensenada', label: 'Ensenada' },
    { value: 'tres_arroyos', label: 'Tres Arroyos' },
    { value: 'dolores', label: 'Dolores' },
    { value: 'chascomus', label: 'Chascomús' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'campana', label: 'Campana' },
    { value: 'chivilcoy', label: 'Chivilcoy' },
    { value: 'bragado', label: 'Bragado' },
    { value: 'carlos_casares', label: 'Carlos Casares' },
    { value: 'balcarce', label: 'Balcarce' },
    { value: 'general_madariaga', label: 'General Madariaga' },
    { value: 'villa_gesell', label: 'Villa Gesell' },
    { value: 'pinamar', label: 'Pinamar' },
    { value: 'necochea', label: 'Necochea' },
    { value: 'benito_juarez', label: 'Benito Juárez' },
    { value: 'laprida', label: 'Laprida' },
    { value: 'pehuajo', label: 'Pehuajó' },
    { value: 'trenque_lauquen', label: 'Trenque Lauquen' },
    { value: 'general_villegas', label: 'General Villegas' },
    { value: 'lincoln', label: 'Lincoln' },
    { value: 'general_pinto', label: 'General Pinto' },
    { value: 'rojas', label: 'Rojas' },
    { value: 'alberti', label: 'Alberti' },
    { value: 'navarro', label: 'Navarro' },
    { value: 'lobos', label: 'Lobos' },
    { value: 'roque_perez', label: 'Roque Pérez' },
    { value: 'saladillo', label: 'Saladillo' },
    { value: 'bolivar', label: 'Bolívar' },
    { value: 'daireaux', label: 'Daireaux' },
    { value: 'henderson', label: 'Henderson' },
    { value: 'hipolito_yrigoyen', label: 'Hipólito Yrigoyen' }
  ],
  'catamarca': [
    { value: 'san_fernando_del_valle_de_catamarca', label: 'San Fernando del Valle de Catamarca' },
    { value: 'belen', label: 'Belén' },
    { value: 'tinogasta', label: 'Tinogasta' },
    { value: 'santa_maria', label: 'Santa María' },
    { value: 'recreo', label: 'Recreo' },
    { value: 'valle_viejo', label: 'Valle Viejo' },
    { value: 'fray_mamerto_esquiu', label: 'Fray Mamerto Esquiú' },
    { value: 'andalgala', label: 'Andalgalá' },
    { value: 'londres', label: 'Londres' },
    { value: 'pomán', label: 'Pomán' },
    { value: 'antofagasta_de_la_sierra', label: 'Antofagasta de la Sierra' },
    { value: 'el_alto', label: 'El Alto' },
    { value: 'icano', label: 'Icaño' },
    { value: 'la_paz', label: 'La Paz' },
    { value: 'capayan', label: 'Capayán' },
    { value: 'paclín', label: 'Paclín' }
  ],
  'chaco': [
    { value: 'resistencia', label: 'Resistencia' },
    { value: 'barranqueras', label: 'Barranqueras' },
    { value: 'presidencia_roque_saenz_pena', label: 'Presidencia Roque Sáenz Peña' },
    { value: 'villa_angela', label: 'Villa Ángela' },
    { value: 'charata', label: 'Charata' },
    { value: 'quitilipi', label: 'Quitilipi' },
    { value: 'machagai', label: 'Machagai' },
    { value: 'juan_jose_castelli', label: 'Juan José Castelli' },
    { value: 'villa_berthet', label: 'Villa Berthet' },
    { value: 'general_jose_de_san_martin', label: 'General José de San Martín' },
    { value: 'tres_isletas', label: 'Tres Isletas' },
    { value: 'pampa_del_infierno', label: 'Pampa del Infierno' },
    { value: 'nueva_pompeya', label: 'Nueva Pompeya' },
    { value: 'miraflores', label: 'Miraflores' },
    { value: 'coronel_du_graty', label: 'Coronel Du Graty' },
    { value: 'corzuela', label: 'Corzuela' },
    { value: 'pinedo', label: 'Pinedo' },
    { value: 'las_breñas', label: 'Las Breñas' },
    { value: 'hermoso_campo', label: 'Hermoso Campo' },
    { value: 'cote_lai', label: 'Cote Lai' }
  ],
  'chubut': [
    { value: 'rawson', label: 'Rawson' },
    { value: 'comodoro_rivadavia', label: 'Comodoro Rivadavia' },
    { value: 'puerto_madryn', label: 'Puerto Madryn' },
    { value: 'trelew', label: 'Trelew' },
    { value: 'esquel', label: 'Esquel' },
    { value: 'gaiman', label: 'Gaiman' },
    { value: 'dolavon', label: 'Dolavon' },
    { value: 'rada_tilly', label: 'Rada Tilly' },
    { value: 'sarmiento', label: 'Sarmiento' },
    { value: 'jose_de_san_martin', label: 'José de San Martín' },
    { value: 'tecka', label: 'Tecka' },
    { value: 'gobernador_costa', label: 'Gobernador Costa' },
    { value: 'camarones', label: 'Camarones' },
    { value: 'gastre', label: 'Gastre' },
    { value: 'gan_gan', label: 'Gan Gan' },
    { value: 'paso_de_indios', label: 'Paso de Indios' },
    { value: 'rio_mayo', label: 'Río Mayo' },
    { value: 'cholila', label: 'Cholila' },
    { value: 'el_hoyo', label: 'El Hoyo' },
    { value: 'lago_puelo', label: 'Lago Puelo' },
    { value: 'el_maiten', label: 'El Maitén' },
    { value: 'cushamen', label: 'Cushamen' }
  ],
  'cordoba': [
    { value: 'cordoba', label: 'Córdoba' },
    { value: 'rio_cuarto', label: 'Río Cuarto' },
    { value: 'villa_maria', label: 'Villa María' },
    { value: 'san_francisco', label: 'San Francisco' },
    { value: 'villa_carlos_paz', label: 'Villa Carlos Paz' },
    { value: 'alta_gracia', label: 'Alta Gracia' },
    { value: 'marcos_juarez', label: 'Marcos Juárez' },
    { value: 'bell_ville', label: 'Bell Ville' },
    { value: 'jesus_maria', label: 'Jesús María' },
    { value: 'la_falda', label: 'La Falda' },
    { value: 'cosquin', label: 'Cosquín' },
    { value: 'villa_dolores', label: 'Villa Dolores' },
    { value: 'dean_funes', label: 'Deán Funes' },
    { value: 'cruz_del_eje', label: 'Cruz del Eje' },
    { value: 'laboulaye', label: 'Laboulaye' },
    { value: 'morteros', label: 'Morteros' },
    { value: 'oncativo', label: 'Oncativo' },
    { value: 'rio_tercero', label: 'Río Tercero' },
    { value: 'arroyito', label: 'Arroyito' },
    { value: 'villa_nueva', label: 'Villa Nueva' },
    { value: 'unquillo', label: 'Unquillo' },
    { value: 'mendiolaza', label: 'Mendiolaza' },
    { value: 'colonia_caroya', label: 'Colonia Caroya' },
    { value: 'monte_cristo', label: 'Monte Cristo' },
    { value: 'porteña', label: 'Porteña' },
    { value: 'freyre', label: 'Freyre' },
    { value: 'devoto', label: 'Devoto' },
    { value: 'las_varillas', label: 'Las Varillas' },
    { value: 'brinkmann', label: 'Brinkmann' },
    { value: 'leones', label: 'Leones' }
  ],
  'corrientes': [
    { value: 'corrientes', label: 'Corrientes' },
    { value: 'goya', label: 'Goya' },
    { value: 'paso_de_los_libres', label: 'Paso de los Libres' },
    { value: 'mercedes', label: 'Mercedes' },
    { value: 'curuzú_cuatiá', label: 'Curuzú Cuatiá' },
    { value: 'esquina', label: 'Esquina' },
    { value: 'monte_caseros', label: 'Monte Caseros' },
    { value: 'sauce', label: 'Sauce' },
    { value: 'bella_vista', label: 'Bella Vista' },
    { value: 'saladas', label: 'Saladas' },
    { value: 'empedrado', label: 'Empedrado' },
    { value: 'mburucuya', label: 'Mburucuyá' },
    { value: 'san_roque', label: 'San Roque' },
    { value: 'concepcion', label: 'Concepción' },
    { value: 'ituzaingo', label: 'Ituzaingó' },
    { value: 'alvear', label: 'Alvear' },
    { value: 'santo_tome', label: 'Santo Tomé' },
    { value: 'virasoro', label: 'Virasoro' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'la_cruz', label: 'La Cruz' },
    { value: 'yapeyú', label: 'Yapeyú' },
    { value: 'gobernador_virasoro', label: 'Gobernador Virasoro' }
  ],
  'entre_rios': [
    { value: 'parana', label: 'Paraná' },
    { value: 'concordia', label: 'Concordia' },
    { value: 'gualeguaychu', label: 'Gualeguaychú' },
    { value: 'uruguay', label: 'Uruguay' },
    { value: 'concepcion_del_uruguay', label: 'Concepción del Uruguay' },
    { value: 'villaguay', label: 'Villaguay' },
    { value: 'crespo', label: 'Crespo' },
    { value: 'nogoya', label: 'Nogoyá' },
    { value: 'victoria', label: 'Victoria' },
    { value: 'diamante', label: 'Diamante' },
    { value: 'san_salvador', label: 'San Salvador' },
    { value: 'chajari', label: 'Chajarí' },
    { value: 'federacion', label: 'Federación' },
    { value: 'colon', label: 'Colón' },
    { value: 'san_jose', label: 'San José' },
    { value: 'la_paz', label: 'La Paz' },
    { value: 'bovril', label: 'Bovril' },
    { value: 'hasenkamp', label: 'Hasenkamp' },
    { value: 'hernandarias', label: 'Hernandarias' },
    { value: 'oro_verde', label: 'Oro Verde' },
    { value: 'cerrito', label: 'Cerrito' },
    { value: 'santa_elena', label: 'Santa Elena' },
    { value: 'rosario_del_tala', label: 'Rosario del Tala' },
    { value: 'san_benito', label: 'San Benito' }
  ],
  'formosa': [
    { value: 'formosa', label: 'Formosa' },
    { value: 'clorinda', label: 'Clorinda' },
    { value: 'pirane', label: 'Pirané' },
    { value: 'el_colorado', label: 'El Colorado' },
    { value: 'ingeniero_juarez', label: 'Ingeniero Juárez' },
    { value: 'las_lomitas', label: 'Las Lomitas' },
    { value: 'comandante_fontana', label: 'Comandante Fontana' },
    { value: 'ibarreta', label: 'Ibarreta' },
    { value: 'laguna_blanca', label: 'Laguna Blanca' },
    { value: 'posta_cambio_zalazar', label: 'Posta Cambio Zalazar' },
    { value: 'general_belgrano', label: 'General Belgrano' },
    { value: 'espinillo', label: 'Espinillo' },
    { value: 'reserva', label: 'Reserva' },
    { value: 'gran_guardia', label: 'Gran Guardia' },
    { value: 'villa_dos_trece', label: 'Villa Dos Trece' }
  ],
  'jujuy': [
    { value: 'san_salvador_de_jujuy', label: 'San Salvador de Jujuy' },
    { value: 'palpala', label: 'Palpalá' },
    { value: 'la_quiaca', label: 'La Quiaca' },
    { value: 'libertador_general_san_martin', label: 'Libertador General San Martín' },
    { value: 'san_pedro', label: 'San Pedro' },
    { value: 'tilcara', label: 'Tilcara' },
    { value: 'humahuaca', label: 'Humahuaca' },
    { value: 'perico', label: 'Perico' },
    { value: 'el_carmen', label: 'El Carmen' },
    { value: 'monterrico', label: 'Monterrico' },
    { value: 'fraile_pintado', label: 'Fraile Pintado' },
    { value: 'calilegua', label: 'Calilegua' },
    { value: 'yuto', label: 'Yuto' },
    { value: 'abra_pampa', label: 'Abra Pampa' },
    { value: 'purmamarca', label: 'Purmamarca' },
    { value: 'maimara', label: 'Maimará' },
    { value: 'volcán', label: 'Volcán' },
    { value: 'tumbaya', label: 'Tumbaya' }
  ],
  'la_pampa': [
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'general_pico', label: 'General Pico' },
    { value: 'toay', label: 'Toay' },
    { value: 'eduardo_castex', label: 'Eduardo Castex' },
    { value: 'realico', label: 'Realicó' },
    { value: 'intendente_alvear', label: 'Intendente Alvear' },
    { value: 'macachín', label: 'Macachín' },
    { value: 'general_acha', label: 'General Acha' },
    { value: 'ingeniero_luiggi', label: 'Ingeniero Luiggi' },
    { value: 'winifreda', label: 'Winifreda' },
    { value: 'catriló', label: 'Catriló' },
    { value: 'victorica', label: 'Victorica' },
    { value: 'rancul', label: 'Rancul' },
    { value: 'jacinto_arauz', label: 'Jacinto Arauz' },
    { value: 'bernardo_larroudé', label: 'Bernardo Larroudé' },
    { value: 'rolón', label: 'Rolón' },
    { value: 'doblas', label: 'Doblas' },
    { value: 'embajador_martini', label: 'Embajador Martini' }
  ],
  'la_rioja': [
    { value: 'la_rioja', label: 'La Rioja' },
    { value: 'chilecito', label: 'Chilecito' },
    { value: 'aimogasta', label: 'Aimogasta' },
    { value: 'chepes', label: 'Chepes' },
    { value: 'chamical', label: 'Chamical' },
    { value: 'villa_union', label: 'Villa Unión' },
    { value: 'famatina', label: 'Famatina' },
    { value: 'nonogasta', label: 'Nonogasta' },
    { value: 'sanagasta', label: 'Sanagasta' },
    { value: 'arauco', label: 'Arauco' },
    { value: 'ulapes', label: 'Ulapes' },
    { value: 'patquia', label: 'Patquía' },
    { value: 'villa_castelli', label: 'Villa Castelli' },
    { value: 'vinchina', label: 'Vinchina' },
    { value: 'tama', label: 'Tama' },
    { value: 'milagro', label: 'Milagro' }
  ],
  'mendoza': [
    { value: 'mendoza', label: 'Mendoza' },
    { value: 'san_rafael', label: 'San Rafael' },
    { value: 'godoy_cruz', label: 'Godoy Cruz' },
    { value: 'las_heras', label: 'Las Heras' },
    { value: 'maipú', label: 'Maipú' },
    { value: 'lujan_de_cuyo', label: 'Luján de Cuyo' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'rivadavia', label: 'Rivadavia' },
    { value: 'guaymallen', label: 'Guaymallén' },
    { value: 'general_alvear', label: 'General Alvear' },
    { value: 'tunuyan', label: 'Tunuyán' },
    { value: 'tupungato', label: 'Tupungato' },
    { value: 'malargüe', label: 'Malargüe' },
    { value: 'san_carlos', label: 'San Carlos' },
    { value: 'lavalle', label: 'Lavalle' },
    { value: 'la_paz', label: 'La Paz' },
    { value: 'santa_rosa', label: 'Santa Rosa' },
    { value: 'junin', label: 'Junín' },
    { value: 'uspallata', label: 'Uspallata' },
    { value: 'cacheuta', label: 'Cacheuta' },
    { value: 'potrerillos', label: 'Potrerillos' },
    { value: 'villa_25_de_mayo', label: 'Villa 25 de Mayo' }
  ],
  'misiones': [
    { value: 'posadas', label: 'Posadas' },
    { value: 'oberá', label: 'Oberá' },
    { value: 'puerto_iguazu', label: 'Puerto Iguazú' },
    { value: 'eldorado', label: 'Eldorado' },
    { value: 'apostoles', label: 'Apóstoles' },
    { value: 'san_vicente', label: 'San Vicente' },
    { value: 'leandro_n_alem', label: 'Leandro N. Alem' },
    { value: 'montecarlo', label: 'Montecarlo' },
    { value: 'wanda', label: 'Wanda' },
    { value: 'puerto_esperanza', label: 'Puerto Esperanza' },
    { value: 'puerto_rico', label: 'Puerto Rico' },
    { value: 'garupa', label: 'Garupá' },
    { value: 'candelaria', label: 'Candelaria' },
    { value: 'jardin_america', label: 'Jardín América' },
    { value: 'santo_pipo', label: 'Santo Pipó' },
    { value: 'dos_de_mayo', label: 'Dos de Mayo' },
    { value: 'san_javier', label: 'San Javier' },
    { value: 'concepcion_de_la_sierra', label: 'Concepción de la Sierra' },
    { value: 'santa_ana', label: 'Santa Ana' },
    { value: 'loreto', label: 'Loreto' },
    { value: 'san_ignacio', label: 'San Ignacio' },
    { value: 'corpus', label: 'Corpus' },
    { value: 'colonia_wanda', label: 'Colonia Wanda' }
  ],
  'neuquen': [
    { value: 'neuquen', label: 'Neuquén' },
    { value: 'cipolletti', label: 'Cipolletti' },
    { value: 'plottier', label: 'Plottier' },
    { value: 'san_martin_de_los_andes', label: 'San Martín de los Andes' },
    { value: 'villa_la_angostura', label: 'Villa La Angostura' },
    { value: 'zapala', label: 'Zapala' },
    { value: 'cutral_co', label: 'Cutral Có' },
    { value: 'plaza_huincul', label: 'Plaza Huincul' },
    { value: 'centenario', label: 'Centenario' },
    { value: 'senillosa', label: 'Senillosa' },
    { value: 'junin_de_los_andes', label: 'Junín de los Andes' },
    { value: 'chos_malal', label: 'Chos Malal' },
    { value: 'rincon_de_los_sauces', label: 'Rincón de los Sauces' },
    { value: 'añelo', label: 'Añelo' },
    { value: 'loncopue', label: 'Loncopué' },
    { value: 'san_patricio_del_chañar', label: 'San Patricio del Chañar' },
    { value: 'villa_pehuenia', label: 'Villa Pehuenia' },
    { value: 'alumine', label: 'Aluminé' },
    { value: 'picun_leufu', label: 'Picún Leufú' },
    { value: 'las_lajas', label: 'Las Lajas' }
  ],
  'rio_negro': [
    { value: 'viedma', label: 'Viedma' },
    { value: 'san_carlos_de_bariloche', label: 'San Carlos de Bariloche' },
    { value: 'general_roca', label: 'General Roca' },
    { value: 'cipolletti', label: 'Cipolletti' },
    { value: 'cinco_saltos', label: 'Cinco Saltos' },
    { value: 'allen', label: 'Allen' },
    { value: 'catriel', label: 'Catriel' },
    { value: 'villa_regina', label: 'Villa Regina' },
    { value: 'fernandez_oro', label: 'Fernández Oro' },
    { value: 'ingeniero_huergo', label: 'Ingeniero Huergo' },
    { value: 'campo_grande', label: 'Campo Grande' },
    { value: 'cervantes', label: 'Cervantes' },
    { value: 'choele_choel', label: 'Choele Choel' },
    { value: 'luis_beltran', label: 'Luis Beltrán' },
    { value: 'lamarque', label: 'Lamarque' },
    { value: 'darwin', label: 'Darwin' },
    { value: 'chimpay', label: 'Chimpay' },
    { value: 'pomona', label: 'Pomona' },
    { value: 'río_colorado', label: 'Río Colorado' },
    { value: 'el_bolson', label: 'El Bolsón' },
    { value: 'dina_huapi', label: 'Dina Huapi' }
  ],
  'salta': [
    { value: 'salta', label: 'Salta' },
    { value: 'san_ramon_de_la_nueva_oran', label: 'San Ramón de la Nueva Orán' },
    { value: 'tartagal', label: 'Tartagal' },
    { value: 'cafayate', label: 'Cafayate' },
    { value: 'metán', label: 'Metán' },
    { value: 'joaquin_v_gonzalez', label: 'Joaquín V. González' },
    { value: 'general_guemes', label: 'General Güemes' },
    { value: 'pichanal', label: 'Pichanal' },
    { value: 'embarcacion', label: 'Embarcación' },
    { value: 'aguaray', label: 'Aguaray' },
    { value: 'general_mosconi', label: 'General Mosconi' },
    { value: 'pocitos', label: 'Pocitos' },
    { value: 'profesor_salvador_mazza', label: 'Profesor Salvador Mazza' },
    { value: 'rosario_de_lerma', label: 'Rosario de Lerma' },
    { value: 'cerrillos', label: 'Cerrillos' },
    { value: 'la_caldera', label: 'La Caldera' },
    { value: 'chicoana', label: 'Chicoana' },
    { value: 'el_carril', label: 'El Carril' },
    { value: 'la_viña', label: 'La Viña' },
    { value: 'cachi', label: 'Cachi' },
    { value: 'molinos', label: 'Molinos' },
    { value: 'san_carlos', label: 'San Carlos' },
    { value: 'angastaco', label: 'Angastaco' },
    { value: 'seclantas', label: 'Seclantas' }
  ],
  'san_juan': [
    { value: 'san_juan', label: 'San Juan' },
    { value: 'rivadavia', label: 'Rivadavia' },
    { value: 'chimbas', label: 'Chimbas' },
    { value: 'rawson', label: 'Rawson' },
    { value: 'pocito', label: 'Pocito' },
    { value: 'santa_lucia', label: 'Santa Lucía' },
    { value: '25_de_mayo', label: '25 de Mayo' },
    { value: 'san_martin', label: 'San Martín' },
    { value: 'caucete', label: 'Caucete' },
    { value: 'jachal', label: 'Jáchal' },
    { value: 'ullum', label: 'Ullum' },
    { value: 'zonda', label: 'Zonda' },
    { value: 'albardón', label: 'Albardón' },
    { value: 'angaco', label: 'Angaco' },
    { value: 'san_agustin_de_valle_fertil', label: 'San Agustín de Valle Fértil' },
    { value: 'iglesia', label: 'Iglesia' },
    { value: 'valle_fertil', label: 'Valle Fértil' },
    { value: 'calingasta', label: 'Calingasta' },
    { value: 'barreal', label: 'Barreal' }
  ],
  'san_luis': [
    { value: 'san_luis', label: 'San Luis' },
    { value: 'villa_mercedes', label: 'Villa Mercedes' },
    { value: 'merlo', label: 'Merlo' },
    { value: 'la_toma', label: 'La Toma' },
    { value: 'tilisarao', label: 'Tilisarao' },
    { value: 'justo_daract', label: 'Justo Daract' },
    { value: 'buena_esperanza', label: 'Buena Esperanza' },
    { value: 'nueva_galia', label: 'Nueva Galia' },
    { value: 'concarán', label: 'Concarán' },
    { value: 'santa_rosa_del_conlara', label: 'Santa Rosa del Conlara' },
    { value: 'villa_de_la_quebrada', label: 'Villa de la Quebrada' },
    { value: 'carpinteria', label: 'Carpintería' },
    { value: 'papagayos', label: 'Papagayos' },
    { value: 'renca', label: 'Renca' },
    { value: 'unión', label: 'Unión' },
    { value: 'candelaria', label: 'Candelaria' },
    { value: 'naschel', label: 'Naschel' },
    { value: 'arizona', label: 'Arizona' }
  ],
  'santa_cruz': [
    { value: 'rio_gallegos', label: 'Río Gallegos' },
    { value: 'caleta_olivia', label: 'Caleta Olivia' },
    { value: 'el_calafate', label: 'El Calafate' },
    { value: 'puerto_santa_cruz', label: 'Puerto Santa Cruz' },
    { value: 'pico_truncado', label: 'Pico Truncado' },
    { value: 'las_heras', label: 'Las Heras' },
    { value: 'puerto_san_julian', label: 'Puerto San Julián' },
    { value: 'rio_turbio', label: 'Río Turbio' },
    { value: 'comandante_luis_piedra_buena', label: 'Comandante Luis Piedra Buena' },
    { value: '28_de_noviembre', label: '28 de Noviembre' },
    { value: 'puerto_deseado', label: 'Puerto Deseado' },
    { value: 'perito_moreno', label: 'Perito Moreno' },
    { value: 'gobernador_gregores', label: 'Gobernador Gregores' },
    { value: 'el_chalten', label: 'El Chaltén' },
    { value: 'tres_lagos', label: 'Tres Lagos' },
    { value: 'jaramillo', label: 'Jaramillo' },
    { value: 'koluel_kaike', label: 'Koluel Kaike' },
    { value: 'fitz_roy', label: 'Fitz Roy' }
  ],
  'santa_fe': [
    { value: 'santa_fe', label: 'Santa Fe' },
    { value: 'rosario', label: 'Rosario' },
    { value: 'rafaela', label: 'Rafaela' },
    { value: 'venado_tuerto', label: 'Venado Tuerto' },
    { value: 'reconquista', label: 'Reconquista' },
    { value: 'esperanza', label: 'Esperanza' },
    { value: 'san_lorenzo', label: 'San Lorenzo' },
    { value: 'casilda', label: 'Casilda' },
    { value: 'villa_gobernador_galvez', label: 'Villa Gobernador Gálvez' },
    { value: 'villa_constitucion', label: 'Villa Constitución' },
    { value: 'san_justo', label: 'San Justo' },
    { value: 'santo_tome', label: 'Santo Tomé' },
    { value: 'sauce_viejo', label: 'Sauce Viejo' },
    { value: 'sunchales', label: 'Sunchales' },
    { value: 'galvez', label: 'Gálvez' },
    { value: 'firmat', label: 'Firmat' },
    { value: 'cañada_de_gomez', label: 'Cañada de Gómez' },
    { value: 'villa_ocampo', label: 'Villa Ocampo' },
    { value: 'avellaneda', label: 'Avellaneda' },
    { value: 'las_rosas', label: 'Las Rosas' },
    { value: 'coronda', label: 'Coronda' },
    { value: 'san_carlos_centro', label: 'San Carlos Centro' },
    { value: 'laguna_paiva', label: 'Laguna Paiva' },
    { value: 'franck', label: 'Franck' },
    { value: 'perez', label: 'Pérez' },
    { value: 'acebal', label: 'Acebal' },
    { value: 'armstrong', label: 'Armstrong' },
    { value: 'las_parejas', label: 'Las Parejas' },
    { value: 'totoras', label: 'Totoras' },
    { value: 'arroyo_seco', label: 'Arroyo Seco' }
  ],
  'santiago_del_estero': [
    { value: 'santiago_del_estero', label: 'Santiago del Estero' },
    { value: 'la_banda', label: 'La Banda' },
    { value: 'termas_de_rio_hondo', label: 'Termas de Río Hondo' },
    { value: 'añatuya', label: 'Añatuya' },
    { value: 'fernandez', label: 'Fernández' },
    { value: 'frías', label: 'Frías' },
    { value: 'monte_quemado', label: 'Monte Quemado' },
    { value: 'bandera', label: 'Bandera' },
    { value: 'quimilí', label: 'Quimilí' },
    { value: 'campo_gallo', label: 'Campo Gallo' },
    { value: 'villa_ojo_de_agua', label: 'Villa Ojo de Agua' },
    { value: 'suncho_corral', label: 'Suncho Corral' },
    { value: 'nueva_esperanza', label: 'Nueva Esperanza' },
    { value: 'los_juríes', label: 'Los Juríes' },
    { value: 'beltrán', label: 'Beltrán' },
    { value: 'villa_la_punta', label: 'Villa La Punta' },
    { value: 'pinto', label: 'Pinto' },
    { value: 'ojo_de_agua', label: 'Ojo de Agua' },
    { value: 'loreto', label: 'Loreto' },
    { value: 'atamisqui', label: 'Atamisqui' }
  ],
  'tierra_del_fuego': [
    { value: 'ushuaia', label: 'Ushuaia' },
    { value: 'rio_grande', label: 'Río Grande' },
    { value: 'tolhuin', label: 'Tolhuin' },
    { value: 'puerto_almanza', label: 'Puerto Almanza' },
    { value: 'puerto_harberton', label: 'Puerto Harberton' },
    { value: 'estancia_harberton', label: 'Estancia Harberton' }
  ],
  'tucuman': [
    { value: 'san_miguel_de_tucuman', label: 'San Miguel de Tucumán' },
    { value: 'yerba_buena', label: 'Yerba Buena' },
    { value: 'tafi_viejo', label: 'Tafí Viejo' },
    { value: 'concepcion', label: 'Concepción' },
    { value: 'banda_del_rio_sali', label: 'Banda del Río Salí' },
    { value: 'alderetes', label: 'Alderetes' },
    { value: 'aguilares', label: 'Aguilares' },
    { value: 'monteros', label: 'Monteros' },
    { value: 'bella_vista', label: 'Bella Vista' },
    { value: 'las_talitas', label: 'Las Talitas' },
    { value: 'famaillá', label: 'Famaillá' },
    { value: 'lules', label: 'Lules' },
    { value: 'trancas', label: 'Trancas' },
    { value: 'burruyacu', label: 'Burruyacú' },
    { value: 'cruz_alta', label: 'Cruz Alta' },
    { value: 'leales', label: 'Leales' },
    { value: 'graneros', label: 'Graneros' },
    { value: 'juan_bautista_alberdi', label: 'Juan Bautista Alberdi' },
    { value: 'rio_chico', label: 'Río Chico' },
    { value: 'tafi_del_valle', label: 'Tafí del Valle' },
    { value: 'amaicha_del_valle', label: 'Amaicha del Valle' },
    { value: 'colalao_del_valle', label: 'Colalao del Valle' },
    { value: 'el_mollar', label: 'El Mollar' }
  ],
  'caba': [
    { value: 'ciudad_autonoma_de_buenos_aires', label: 'Ciudad Autónoma de Buenos Aires' }
  ]
};