export interface SelectOption {
  value: string;
  label: string;
}

export interface GeographicData {
  provincias: SelectOption[];
  departamentosPorProvincia: { [key: string]: SelectOption[] };
  ciudadesPorProvincia: { [key: string]: SelectOption[] };
}

export const provinciaOptions: SelectOption[] = [
  { value: 'Buenos Aires', label: 'Buenos Aires' },
  { value: 'Catamarca', label: 'Catamarca' },
  { value: 'Chaco', label: 'Chaco' },
  { value: 'Chubut', label: 'Chubut' },
  { value: 'Córdoba', label: 'Córdoba' },
  { value: 'Corrientes', label: 'Corrientes' },
  { value: 'Entre Ríos', label: 'Entre Ríos' },
  { value: 'Formosa', label: 'Formosa' },
  { value: 'Jujuy', label: 'Jujuy' },
  { value: 'La Pampa', label: 'La Pampa' },
  { value: 'La Rioja', label: 'La Rioja' },
  { value: 'Mendoza', label: 'Mendoza' },
  { value: 'Misiones', label: 'Misiones' },
  { value: 'Neuquén', label: 'Neuquén' },
  { value: 'Río Negro', label: 'Río Negro' },
  { value: 'Salta', label: 'Salta' },
  { value: 'San Juan', label: 'San Juan' },
  { value: 'San Luis', label: 'San Luis' },
  { value: 'Santa Cruz', label: 'Santa Cruz' },
  { value: 'Santa Fe', label: 'Santa Fe' },
  { value: 'Santiago del Estero', label: 'Santiago del Estero' },
  { value: 'Tierra del Fuego', label: 'Tierra del Fuego' },
  { value: 'Tucumán', label: 'Tucumán' },
  { value: 'Ciudad Autónoma de Buenos Aires', label: 'Ciudad Autónoma de Buenos Aires' }
];

export const departamentosPorProvincia: { [key: string]: SelectOption[] } = {
  'Buenos Aires': [
    { value: 'Adolfo Alsina', label: 'Adolfo Alsina' },
    { value: 'Adolfo Gonzales Chaves', label: 'Adolfo Gonzales Chaves' },
    { value: 'Alberti', label: 'Alberti' },
    { value: 'Almirante Brown', label: 'Almirante Brown' },
    { value: 'Arrecifes', label: 'Arrecifes' },
    { value: 'Avellaneda', label: 'Avellaneda' },
    { value: 'Ayacucho', label: 'Ayacucho' },
    { value: 'Azul', label: 'Azul' },
    { value: 'Bahía Blanca', label: 'Bahía Blanca' },
    { value: 'Balcarce', label: 'Balcarce' },
    { value: 'Baradero', label: 'Baradero' },
    { value: 'Benito Juárez', label: 'Benito Juárez' },
    { value: 'Berazategui', label: 'Berazategui' },
    { value: 'Berisso', label: 'Berisso' },
    { value: 'Bolívar', label: 'Bolívar' },
    { value: 'Bragado', label: 'Bragado' },
    { value: 'Brandsen', label: 'Brandsen' },
    { value: 'Campana', label: 'Campana' },
    { value: 'Cañuelas', label: 'Cañuelas' },
    { value: 'Capitán Sarmiento', label: 'Capitán Sarmiento' },
    { value: 'Carlos Casares', label: 'Carlos Casares' },
    { value: 'Carlos Tejedor', label: 'Carlos Tejedor' },
    { value: 'Carmen de Areco', label: 'Carmen de Areco' },
    { value: 'Castelli', label: 'Castelli' },
    { value: 'Chascomús', label: 'Chascomús' },
    { value: 'Chivilcoy', label: 'Chivilcoy' },
    { value: 'Colón', label: 'Colón' },
    { value: 'Coronel Dorrego', label: 'Coronel Dorrego' },
    { value: 'Coronel Pringles', label: 'Coronel Pringles' },
    { value: 'Coronel Rosales', label: 'Coronel Rosales' },
    { value: 'Coronel Suárez', label: 'Coronel Suárez' },
    { value: 'Daireaux', label: 'Daireaux' },
    { value: 'Dolores', label: 'Dolores' },
    { value: 'Ensenada', label: 'Ensenada' },
    { value: 'Escobar', label: 'Escobar' },
    { value: 'Esteban Echeverría', label: 'Esteban Echeverría' },
    { value: 'Exaltación de la Cruz', label: 'Exaltación de la Cruz' },
    { value: 'Ezeiza', label: 'Ezeiza' },
    { value: 'Florencio Varela', label: 'Florencio Varela' },
    { value: 'General Alvarado', label: 'General Alvarado' },
    { value: 'General Alvear', label: 'General Alvear' },
    { value: 'General Arenales', label: 'General Arenales' },
    { value: 'General Belgrano', label: 'General Belgrano' },
    { value: 'General Guido', label: 'General Guido' },
    { value: 'General La Madrid', label: 'General La Madrid' },
    { value: 'General Las Heras', label: 'General Las Heras' },
    { value: 'General Lavalle', label: 'General Lavalle' },
    { value: 'General Madariaga', label: 'General Madariaga' },
    { value: 'General Paz', label: 'General Paz' },
    { value: 'General Pinto', label: 'General Pinto' },
    { value: 'General Pueyrredón', label: 'General Pueyrredón' },
    { value: 'General Rodríguez', label: 'General Rodríguez' },
    { value: 'General San Martín', label: 'General San Martín' },
    { value: 'General Viamonte', label: 'General Viamonte' },
    { value: 'General Villegas', label: 'General Villegas' },
    { value: 'Guaminí', label: 'Guaminí' },
    { value: 'Hipólito Yrigoyen', label: 'Hipólito Yrigoyen' },
    { value: 'Hurlingham', label: 'Hurlingham' },
    { value: 'Ituzaingó', label: 'Ituzaingó' },
    { value: 'José C. Paz', label: 'José C. Paz' },
    { value: 'Junín', label: 'Junín' },
    { value: 'La Costa', label: 'La Costa' },
    { value: 'La Matanza', label: 'La Matanza' },
    { value: 'La Plata', label: 'La Plata' },
    { value: 'Lanús', label: 'Lanús' },
    { value: 'Laprida', label: 'Laprida' },
    { value: 'Las Flores', label: 'Las Flores' },
    { value: 'Leandro N. Alem', label: 'Leandro N. Alem' },
    { value: 'Lincoln', label: 'Lincoln' },
    { value: 'Lobería', label: 'Lobería' },
    { value: 'Lobos', label: 'Lobos' },
    { value: 'Lomas de Zamora', label: 'Lomas de Zamora' },
    { value: 'Luján', label: 'Luján' },
    { value: 'Magdalena', label: 'Magdalena' },
    { value: 'Maipú', label: 'Maipú' },
    { value: 'Malvinas Argentinas', label: 'Malvinas Argentinas' },
    { value: 'Mar Chiquita', label: 'Mar Chiquita' },
    { value: 'Marcos Paz', label: 'Marcos Paz' },
    { value: 'Mercedes', label: 'Mercedes' },
    { value: 'Merlo', label: 'Merlo' },
    { value: 'Monte', label: 'Monte' },
    { value: 'Monte Hermoso', label: 'Monte Hermoso' },
    { value: 'Moreno', label: 'Moreno' },
    { value: 'Morón', label: 'Morón' },
    { value: 'Navarro', label: 'Navarro' },
    { value: 'Necochea', label: 'Necochea' },
    { value: 'Nueve de Julio', label: 'Nueve de Julio' },
    { value: 'Olavarría', label: 'Olavarría' },
    { value: 'Patagones', label: 'Patagones' },
    { value: 'Pehuajó', label: 'Pehuajó' },
    { value: 'Pellegrini', label: 'Pellegrini' },
    { value: 'Pergamino', label: 'Pergamino' },
    { value: 'Pila', label: 'Pila' },
    { value: 'Pilar', label: 'Pilar' },
    { value: 'Pinamar', label: 'Pinamar' },
    { value: 'Presidente Perón', label: 'Presidente Perón' },
    { value: 'Puán', label: 'Puán' },
    { value: 'Punta Indio', label: 'Punta Indio' },
    { value: 'Quilmes', label: 'Quilmes' },
    { value: 'Ramallo', label: 'Ramallo' },
    { value: 'Rauch', label: 'Rauch' },
    { value: 'Rivadavia', label: 'Rivadavia' },
    { value: 'Rojas', label: 'Rojas' },
    { value: 'Roque Pérez', label: 'Roque Pérez' },
    { value: 'Saavedra', label: 'Saavedra' },
    { value: 'Saladillo', label: 'Saladillo' },
    { value: 'Salliqueló', label: 'Salliqueló' },
    { value: 'Salto', label: 'Salto' },
    { value: 'San Andrés de Giles', label: 'San Andrés de Giles' },
    { value: 'San Antonio de Areco', label: 'San Antonio de Areco' },
    { value: 'San Cayetano', label: 'San Cayetano' },
    { value: 'San Fernando', label: 'San Fernando' },
    { value: 'San Isidro', label: 'San Isidro' },
    { value: 'San Miguel', label: 'San Miguel' },
    { value: 'San Nicolás', label: 'San Nicolás' },
    { value: 'San Pedro', label: 'San Pedro' },
    { value: 'San Vicente', label: 'San Vicente' },
    { value: 'Suipacha', label: 'Suipacha' },
    { value: 'Tandil', label: 'Tandil' },
    { value: 'Tapalqué', label: 'Tapalqué' },
    { value: 'Tigre', label: 'Tigre' },
    { value: 'Tordillo', label: 'Tordillo' },
    { value: 'Tornquist', label: 'Tornquist' },
    { value: 'Trenque Lauquen', label: 'Trenque Lauquen' },
    { value: 'Tres Arroyos', label: 'Tres Arroyos' },
    { value: 'Tres de Febrero', label: 'Tres de Febrero' },
    { value: 'Tres Lomas', label: 'Tres Lomas' },
    { value: 'Veinticinco de Mayo', label: 'Veinticinco de Mayo' },
    { value: 'Vicente López', label: 'Vicente López' },
    { value: 'Villa Gesell', label: 'Villa Gesell' },
    { value: 'Villarino', label: 'Villarino' },
    { value: 'Zárate', label: 'Zárate' }
  ],
  'Catamarca': [
    { value: 'Ambato', label: 'Ambato' },
    { value: 'Ancasti', label: 'Ancasti' },
    { value: 'Andalgalá', label: 'Andalgalá' },
    { value: 'Antofagasta de la Sierra', label: 'Antofagasta de la Sierra' },
    { value: 'Belén', label: 'Belén' },
    { value: 'Capayán', label: 'Capayán' },
    { value: 'Capital', label: 'Capital' },
    { value: 'El Alto', label: 'El Alto' },
    { value: 'Fray Mamerto Esquiú', label: 'Fray Mamerto Esquiú' },
    { value: 'La Paz', label: 'La Paz' },
    { value: 'Paclín', label: 'Paclín' },
    { value: 'Pomán', label: 'Pomán' },
    { value: 'Santa María', label: 'Santa María' },
    { value: 'Santa Rosa', label: 'Santa Rosa' },
    { value: 'Tinogasta', label: 'Tinogasta' },
    { value: 'Valle Viejo', label: 'Valle Viejo' }
  ],
  'Chaco': [
    { value: 'Almirante Brown', label: 'Almirante Brown' },
    { value: 'Bermejo', label: 'Bermejo' },
    { value: 'Chacabuco', label: 'Chacabuco' },
    { value: 'Comandante Fernández', label: 'Comandante Fernández' },
    { value: 'Dos de Mayo', label: 'Dos de Mayo' },
    { value: 'Fray Justo Santa María de Oro', label: 'Fray Justo Santa María de Oro' },
    { value: 'General Belgrano', label: 'General Belgrano' },
    { value: 'General Donovan', label: 'General Donovan' },
    { value: 'General Güemes', label: 'General Güemes' },
    { value: 'Independencia', label: 'Independencia' },
    { value: 'Libertad', label: 'Libertad' },
    { value: 'Libertador General San Martín', label: 'Libertador General San Martín' },
    { value: 'Maipú', label: 'Maipú' },
    { value: 'Mayor Luis J. Fontana', label: 'Mayor Luis J. Fontana' },
    { value: 'Nueve de Julio', label: 'Nueve de Julio' },
    { value: 'O\'Higgins', label: 'O\'Higgins' },
    { value: 'Presidencia de la Plaza', label: 'Presidencia de la Plaza' },
    { value: 'Primero de Mayo', label: 'Primero de Mayo' },
    { value: 'Quitilipi', label: 'Quitilipi' },
    { value: 'San Fernando', label: 'San Fernando' },
    { value: 'San Lorenzo', label: 'San Lorenzo' },
    { value: 'Sargento Cabral', label: 'Sargento Cabral' },
    { value: 'Tapenagá', label: 'Tapenagá' },
    { value: 'Veinticinco de Mayo', label: 'Veinticinco de Mayo' }
  ],
  'Chubut': [
    { value: 'Biedma', label: 'Biedma' },
    { value: 'Cushamen', label: 'Cushamen' },
    { value: 'Escalante', label: 'Escalante' },
    { value: 'Florentino Ameghino', label: 'Florentino Ameghino' },
    { value: 'Futaleufú', label: 'Futaleufú' },
    { value: 'Gaiman', label: 'Gaiman' },
    { value: 'Gastre', label: 'Gastre' },
    { value: 'Languiñeo', label: 'Languiñeo' },
    { value: 'Mártires', label: 'Mártires' },
    { value: 'Paso de Indios', label: 'Paso de Indios' },
    { value: 'Rawson', label: 'Rawson' },
    { value: 'Río Senguer', label: 'Río Senguer' },
    { value: 'Sarmiento', label: 'Sarmiento' },
    { value: 'Tehuelches', label: 'Tehuelches' },
    { value: 'Telsen', label: 'Telsen' }
  ],
  'Córdoba': [
    { value: 'Calamuchita', label: 'Calamuchita' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Colón', label: 'Colón' },
    { value: 'Cruz del Eje', label: 'Cruz del Eje' },
    { value: 'General Roca', label: 'General Roca' },
    { value: 'General San Martín', label: 'General San Martín' },
    { value: 'Ischilin', label: 'Ischilin' },
    { value: 'Juárez Celman', label: 'Juárez Celman' },
    { value: 'Marcos Juárez', label: 'Marcos Juárez' },
    { value: 'Minas', label: 'Minas' },
    { value: 'Pocho', label: 'Pocho' },
    { value: 'Presidente Roque Sáenz Peña', label: 'Presidente Roque Sáenz Peña' },
    { value: 'Punilla', label: 'Punilla' },
    { value: 'Río Cuarto', label: 'Río Cuarto' },
    { value: 'Río Primero', label: 'Río Primero' },
    { value: 'Río Seco', label: 'Río Seco' },
    { value: 'Río Segundo', label: 'Río Segundo' },
    { value: 'San Alberto', label: 'San Alberto' },
    { value: 'San Javier', label: 'San Javier' },
    { value: 'San Justo', label: 'San Justo' },
    { value: 'Santa María', label: 'Santa María' },
    { value: 'Sobremonte', label: 'Sobremonte' },
    { value: 'Tercero Arriba', label: 'Tercero Arriba' },
    { value: 'Totoral', label: 'Totoral' },
    { value: 'Tulumba', label: 'Tulumba' },
    { value: 'Unión', label: 'Unión' }
  ],
  'Corrientes': [
    { value: 'Bella Vista', label: 'Bella Vista' },
    { value: 'Berón de Astrada', label: 'Berón de Astrada' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Concepción', label: 'Concepción' },
    { value: 'Curuzú Cuatiá', label: 'Curuzú Cuatiá' },
    { value: 'Empedrado', label: 'Empedrado' },
    { value: 'Esquina', label: 'Esquina' },
    { value: 'General Alvear', label: 'General Alvear' },
    { value: 'General Paz', label: 'General Paz' },
    { value: 'Goya', label: 'Goya' },
    { value: 'Itatí', label: 'Itatí' },
    { value: 'Ituzaingó', label: 'Ituzaingó' },
    { value: 'Lavalle', label: 'Lavalle' },
    { value: 'Mburucuyá', label: 'Mburucuyá' },
    { value: 'Mercedes', label: 'Mercedes' },
    { value: 'Monte Caseros', label: 'Monte Caseros' },
    { value: 'Paso de los Libres', label: 'Paso de los Libres' },
    { value: 'Saladas', label: 'Saladas' },
    { value: 'San Cosme', label: 'San Cosme' },
    { value: 'San Luis del Palmar', label: 'San Luis del Palmar' },
    { value: 'San Martín', label: 'San Martín' },
    { value: 'San Miguel', label: 'San Miguel' },
    { value: 'San Roque', label: 'San Roque' },
    { value: 'Santo Tomé', label: 'Santo Tomé' },
    { value: 'Sauce', label: 'Sauce' }
  ],
  'Entre Ríos': [
    { value: 'Colón', label: 'Colón' },
    { value: 'Concordia', label: 'Concordia' },
    { value: 'Diamante', label: 'Diamante' },
    { value: 'Federación', label: 'Federación' },
    { value: 'Federó', label: 'Federó' },
    { value: 'Feliciano', label: 'Feliciano' },
    { value: 'Gualeguay', label: 'Gualeguay' },
    { value: 'Gualeguaychú', label: 'Gualeguaychú' },
    { value: 'Islas del Ibicuy', label: 'Islas del Ibicuy' },
    { value: 'La Paz', label: 'La Paz' },
    { value: 'Nogoyá', label: 'Nogoyá' },
    { value: 'Paraná', label: 'Paraná' },
    { value: 'San Salvador', label: 'San Salvador' },
    { value: 'Tala', label: 'Tala' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Victoria', label: 'Victoria' },
    { value: 'Villaguay', label: 'Villaguay' }
  ],
  'Formosa': [
    { value: 'Bermejo', label: 'Bermejo' },
    { value: 'Formosa', label: 'Formosa' },
    { value: 'Laishí', label: 'Laishí' },
    { value: 'Matacos', label: 'Matacos' },
    { value: 'Patiño', label: 'Patiño' },
    { value: 'Pilagás', label: 'Pilagás' },
    { value: 'Pilcomayo', label: 'Pilcomayo' },
    { value: 'Ramón Lista', label: 'Ramón Lista' },
    { value: 'Pirané', label: 'Pirané' }
  ],
  'Jujuy': [
    { value: 'Cochinoca', label: 'Cochinoca' },
    { value: 'Dr. Manuel Belgrano', label: 'Dr. Manuel Belgrano' },
    { value: 'El Carmen', label: 'El Carmen' },
    { value: 'Humahuaca', label: 'Humahuaca' },
    { value: 'Ledesma', label: 'Ledesma' },
    { value: 'Palpalá', label: 'Palpalá' },
    { value: 'Rinconada', label: 'Rinconada' },
    { value: 'San Antonio', label: 'San Antonio' },
    { value: 'San Pedro', label: 'San Pedro' },
    { value: 'Santa Bárbara', label: 'Santa Bárbara' },
    { value: 'Susques', label: 'Susques' },
    { value: 'Tilcara', label: 'Tilcara' },
    { value: 'Tumbaya', label: 'Tumbaya' },
    { value: 'Valle Grande', label: 'Valle Grande' },
    { value: 'Yavi', label: 'Yavi' }
  ],
  'La Pampa': [
    { value: 'Atreucó', label: 'Atreucó' },
    { value: 'Caleu Caleu', label: 'Caleu Caleu' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Catriló', label: 'Catriló' },
    { value: 'Chalileo', label: 'Chalileo' },
    { value: 'Chapaleufú', label: 'Chapaleufú' },
    { value: 'Conhelo', label: 'Conhelo' },
    { value: 'Curacó', label: 'Curacó' },
    { value: 'Guatraché', label: 'Guatraché' },
    { value: 'Hucal', label: 'Hucal' },
    { value: 'Lihuel Calel', label: 'Lihuel Calel' },
    { value: 'Limay Mahuida', label: 'Limay Mahuida' },
    { value: 'Loventué', label: 'Loventué' },
    { value: 'Maracó', label: 'Maracó' },
    { value: 'Puelén', label: 'Puelén' },
    { value: 'Quemú Quemú', label: 'Quemú Quemú' },
    { value: 'Rancul', label: 'Rancul' },
    { value: 'Realicó', label: 'Realicó' },
    { value: 'Toay', label: 'Toay' },
    { value: 'Trenel', label: 'Trenel' },
    { value: 'Utracán', label: 'Utracán' }
  ],
  'La Rioja': [
    { value: 'Ángel Vicente Peñaloza', label: 'Ángel Vicente Peñaloza' },
    { value: 'Arauco', label: 'Arauco' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Castro Barros', label: 'Castro Barros' },
    { value: 'Chamical', label: 'Chamical' },
    { value: 'Chilecito', label: 'Chilecito' },
    { value: 'Coronel Felipe Varela', label: 'Coronel Felipe Varela' },
    { value: 'Famatina', label: 'Famatina' },
    { value: 'General Belgrano', label: 'General Belgrano' },
    { value: 'General Juan Facundo Quiroga', label: 'General Juan Facundo Quiroga' },
    { value: 'General Lamadrid', label: 'General Lamadrid' },
    { value: 'General Ocampo', label: 'General Ocampo' },
    { value: 'General San Martín', label: 'General San Martín' },
    { value: 'Independencia', label: 'Independencia' },
    { value: 'Rosario Vera Peñaloza', label: 'Rosario Vera Peñaloza' },
    { value: 'San Blas de los Sauces', label: 'San Blas de los Sauces' },
    { value: 'Sanagasta', label: 'Sanagasta' },
    { value: 'Vinchina', label: 'Vinchina' }
  ],
  'Mendoza': [
    { value: 'Capital', label: 'Capital' },
    { value: 'General Alvear', label: 'General Alvear' },
    { value: 'Godoy Cruz', label: 'Godoy Cruz' },
    { value: 'Guaymallén', label: 'Guaymallén' },
    { value: 'Junín', label: 'Junín' },
    { value: 'La Paz', label: 'La Paz' },
    { value: 'Las Heras', label: 'Las Heras' },
    { value: 'Lavalle', label: 'Lavalle' },
    { value: 'Luján de Cuyo', label: 'Luján de Cuyo' },
    { value: 'Maipú', label: 'Maipú' },
    { value: 'Malargüe', label: 'Malargüe' },
    { value: 'Rivadavia', label: 'Rivadavia' },
    { value: 'San Carlos', label: 'San Carlos' },
    { value: 'San Martín', label: 'San Martín' },
    { value: 'San Rafael', label: 'San Rafael' },
    { value: 'Santa Rosa', label: 'Santa Rosa' },
    { value: 'Tunuyán', label: 'Tunuyán' },
    { value: 'Tupungato', label: 'Tupungato' }
  ],
  'Misiones': [
    { value: 'Apóstoles', label: 'Apóstoles' },
    { value: 'Cainguás', label: 'Cainguás' },
    { value: 'Candelaria', label: 'Candelaria' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Concepción', label: 'Concepción' },
    { value: 'Eldorado', label: 'Eldorado' },
    { value: 'General Manuel Belgrano', label: 'General Manuel Belgrano' },
    { value: 'Guaraní', label: 'Guaraní' },
    { value: 'Iguazú', label: 'Iguazú' },
    { value: 'Leandro N. Alem', label: 'Leandro N. Alem' },
    { value: 'Libertador General San Martín', label: 'Libertador General San Martín' },
    { value: 'Montecarlo', label: 'Montecarlo' },
    { value: 'Oberá', label: 'Oberá' },
    { value: 'San Ignacio', label: 'San Ignacio' },
    { value: 'San Javier', label: 'San Javier' },
    { value: 'San Martín', label: 'San Martín' },
    { value: 'San Pedro', label: 'San Pedro' }
  ],
  'Neuquén': [
    { value: 'Aluminé', label: 'Aluminé' },
    { value: 'Añelo', label: 'Añelo' },
    { value: 'Catán Lil', label: 'Catán Lil' },
    { value: 'Chos Malal', label: 'Chos Malal' },
    { value: 'Collón Curá', label: 'Collón Curá' },
    { value: 'Confluencia', label: 'Confluencia' },
    { value: 'Huiliches', label: 'Huiliches' },
    { value: 'Lácar', label: 'Lácar' },
    { value: 'Loncopué', label: 'Loncopué' },
    { value: 'Los Lagos', label: 'Los Lagos' },
    { value: 'Minas', label: 'Minas' },
    { value: 'Ñorquín', label: 'Ñorquín' },
    { value: 'Pehuenches', label: 'Pehuenches' },
    { value: 'Picún Leufú', label: 'Picún Leufú' },
    { value: 'Picunches', label: 'Picunches' },
    { value: 'Zapala', label: 'Zapala' }
  ],
  'Río Negro': [
    { value: 'Adolfo Alsina', label: 'Adolfo Alsina' },
    { value: 'Avellaneda', label: 'Avellaneda' },
    { value: 'Bariloche', label: 'Bariloche' },
    { value: 'Conesa', label: 'Conesa' },
    { value: 'El Cuy', label: 'El Cuy' },
    { value: 'General Roca', label: 'General Roca' },
    { value: 'Ñorquinco', label: 'Ñorquinco' },
    { value: 'Nueve de Julio', label: 'Nueve de Julio' },
    { value: 'Pico', label: 'Pico' },
    { value: 'Pilcaniyeu', label: 'Pilcaniyeu' },
    { value: 'San Antonio', label: 'San Antonio' },
    { value: 'Valcheta', label: 'Valcheta' },
    { value: 'Viedma', label: 'Viedma' }
  ],
  'Salta': [
    { value: 'Anta', label: 'Anta' },
    { value: 'Cachi', label: 'Cachi' },
    { value: 'Cafayate', label: 'Cafayate' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Cerrillos', label: 'Cerrillos' },
    { value: 'Chicoana', label: 'Chicoana' },
    { value: 'General Güemes', label: 'General Güemes' },
    { value: 'General José de San Martín', label: 'General José de San Martín' },
    { value: 'Guachipas', label: 'Guachipas' },
    { value: 'Iruya', label: 'Iruya' },
    { value: 'La Caldera', label: 'La Caldera' },
    { value: 'La Candelaria', label: 'La Candelaria' },
    { value: 'La Poma', label: 'La Poma' },
    { value: 'La Viña', label: 'La Viña' },
    { value: 'Los Andes', label: 'Los Andes' },
    { value: 'Metán', label: 'Metán' },
    { value: 'Molinos', label: 'Molinos' },
    { value: 'Orán', label: 'Orán' },
    { value: 'Rivadavia', label: 'Rivadavia' },
    { value: 'Rosario de Lerma', label: 'Rosario de Lerma' },
    { value: 'Rosario de la Frontera', label: 'Rosario de la Frontera' },
    { value: 'San Carlos', label: 'San Carlos' },
    { value: 'Santa Victoria', label: 'Santa Victoria' }
  ],
  'San Juan': [
    { value: '25 de Mayo', label: '25 de Mayo' },
    { value: 'Albardón', label: 'Albardón' },
    { value: 'Angaco', label: 'Angaco' },
    { value: 'Calingasta', label: 'Calingasta' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Caucete', label: 'Caucete' },
    { value: 'Chimbas', label: 'Chimbas' },
    { value: 'Iglesia', label: 'Iglesia' },
    { value: 'Jáchal', label: 'Jáchal' },
    { value: 'Pocito', label: 'Pocito' },
    { value: 'Rawson', label: 'Rawson' },
    { value: 'Rivadavia', label: 'Rivadavia' },
    { value: 'San Martín', label: 'San Martín' },
    { value: 'Santa Lucía', label: 'Santa Lucía' },
    { value: 'Sarmiento', label: 'Sarmiento' },
    { value: 'Ullum', label: 'Ullum' },
    { value: 'Valle Fértil', label: 'Valle Fértil' },
    { value: 'Zonda', label: 'Zonda' }
  ],
  'San Luis': [
    { value: 'Ayacucho', label: 'Ayacucho' },
    { value: 'Belgrano', label: 'Belgrano' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Chacabuco', label: 'Chacabuco' },
    { value: 'Coronel Pringles', label: 'Coronel Pringles' },
    { value: 'Dupuy', label: 'Dupuy' },
    { value: 'General Pedernera', label: 'General Pedernera' },
    { value: 'Gobernador Dupuy', label: 'Gobernador Dupuy' },
    { value: 'Junín', label: 'Junín' },
    { value: 'La Capital', label: 'La Capital' },
    { value: 'Libertador General San Martín', label: 'Libertador General San Martín' }
  ],
  'Santa Cruz': [
    { value: 'Corpen Aike', label: 'Corpen Aike' },
    { value: 'Deseado', label: 'Deseado' },
    { value: 'Güer Aike', label: 'Güer Aike' },
    { value: 'Lago Argentino', label: 'Lago Argentino' },
    { value: 'Lago Buenos Aires', label: 'Lago Buenos Aires' },
    { value: 'Magallanes', label: 'Magallanes' },
    { value: 'Río Chico', label: 'Río Chico' }
  ],
  'Santa Fe': [
    { value: 'Belgrano', label: 'Belgrano' },
    { value: 'Caseros', label: 'Caseros' },
    { value: 'Castellanos', label: 'Castellanos' },
    { value: 'Constitución', label: 'Constitución' },
    { value: 'Garay', label: 'Garay' },
    { value: 'General López', label: 'General López' },
    { value: 'General Obligado', label: 'General Obligado' },
    { value: 'Iriondo', label: 'Iriondo' },
    { value: 'La Capital', label: 'La Capital' },
    { value: 'Las Colonias', label: 'Las Colonias' },
    { value: 'Nueve de Julio', label: 'Nueve de Julio' },
    { value: 'Rosario', label: 'Rosario' },
    { value: 'San Cristóbal', label: 'San Cristóbal' },
    { value: 'San Javier', label: 'San Javier' },
    { value: 'San Jerónimo', label: 'San Jerónimo' },
    { value: 'San Justo', label: 'San Justo' },
    { value: 'San Lorenzo', label: 'San Lorenzo' },
    { value: 'San Martín', label: 'San Martín' },
    { value: 'Vera', label: 'Vera' }
  ],
  'Santiago del Estero': [
    { value: 'Aguirre', label: 'Aguirre' },
    { value: 'Alberdi', label: 'Alberdi' },
    { value: 'Atamisqui', label: 'Atamisqui' },
    { value: 'Avellaneda', label: 'Avellaneda' },
    { value: 'Banda', label: 'Banda' },
    { value: 'Belgrano', label: 'Belgrano' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Caseros', label: 'Caseros' },
    { value: 'Choya', label: 'Choya' },
    { value: 'Copo', label: 'Copo' },
    { value: 'Figueroa', label: 'Figueroa' },
    { value: 'General Taboada', label: 'General Taboada' },
    { value: 'Guasayán', label: 'Guasayán' },
    { value: 'Ibarra', label: 'Ibarra' },
    { value: 'Jiménez', label: 'Jiménez' },
    { value: 'Juan Felipe Ibarra', label: 'Juan Felipe Ibarra' },
    { value: 'Loreto', label: 'Loreto' },
    { value: 'Mitre', label: 'Mitre' },
    { value: 'Moreno', label: 'Moreno' },
    { value: 'Ojo de Agua', label: 'Ojo de Agua' },
    { value: 'Pellegrini', label: 'Pellegrini' },
    { value: 'Quebrachos', label: 'Quebrachos' },
    { value: 'Río Hondo', label: 'Río Hondo' },
    { value: 'Rivadavia', label: 'Rivadavia' },
    { value: 'Robles', label: 'Robles' },
    { value: 'Salavina', label: 'Salavina' },
    { value: 'San Martín', label: 'San Martín' },
    { value: 'Sarmiento', label: 'Sarmiento' },
    { value: 'Silípica', label: 'Silípica' }
  ],
  'Tierra del Fuego': [
    { value: 'Río Grande', label: 'Río Grande' },
    { value: 'Ushuaia', label: 'Ushuaia' }
  ],
  'Tucumán': [
    { value: 'Burruyacú', label: 'Burruyacú' },
    { value: 'Capital', label: 'Capital' },
    { value: 'Chicligasta', label: 'Chicligasta' },
    { value: 'Cruz Alta', label: 'Cruz Alta' },
    { value: 'Famaillá', label: 'Famaillá' },
    { value: 'Graneros', label: 'Graneros' },
    { value: 'Juan Bautista Alberdi', label: 'Juan Bautista Alberdi' },
    { value: 'La Cocha', label: 'La Cocha' },
    { value: 'Leales', label: 'Leales' },
    { value: 'Lules', label: 'Lules' },
    { value: 'Monteros', label: 'Monteros' },
    { value: 'Río Chico', label: 'Río Chico' },
    { value: 'Simoca', label: 'Simoca' },
    { value: 'Tafí del Valle', label: 'Tafí del Valle' },
    { value: 'Tafí Viejo', label: 'Tafí Viejo' },
    { value: 'Trancas', label: 'Trancas' },
    { value: 'Yerba Buena', label: 'Yerba Buena' }
  ],
  'Ciudad Autónoma de Buenos Aires': [
    { value: 'Comuna 1 (Retiro, San Nicolás, Puerto Madero, San Telmo, Montserrat, Constitución)', label: 'Comuna 1 (Retiro, San Nicolás, Puerto Madero, San Telmo, Montserrat, Constitución)' },
    { value: 'Comuna 2 (Recoleta)', label: 'Comuna 2 (Recoleta)' },
    { value: 'Comuna 3 (Balvanera, San Cristóbal)', label: 'Comuna 3 (Balvanera, San Cristóbal)' },
    { value: 'Comuna 4 (La Boca, Barracas, Parque Patricios, Nueva Pompeya)', label: 'Comuna 4 (La Boca, Barracas, Parque Patricios, Nueva Pompeya)' },
    { value: 'Comuna 5 (Boedo, Almagro)', label: 'Comuna 5 (Boedo, Almagro)' },
    { value: 'Comuna 6 (Caballito)', label: 'Comuna 6 (Caballito)' },
    { value: 'Comuna 7 (Flores, Parque Chacabuco)', label: 'Comuna 7 (Flores, Parque Chacabuco)' },
    { value: 'Comuna 8 (Villa Soldati, Villa Riachuelo, Villa Lugano)', label: 'Comuna 8 (Villa Soldati, Villa Riachuelo, Villa Lugano)' },
    { value: 'Comuna 9 (Liniers, Mataderos, Parque Avellaneda)', label: 'Comuna 9 (Liniers, Mataderos, Parque Avellaneda)' },
    { value: 'Comuna 10 (Villa Real, Monte Castro, Versalles, Floresta, Vélez Sársfield, Villa Luro)', label: 'Comuna 10 (Villa Real, Monte Castro, Versalles, Floresta, Vélez Sársfield, Villa Luro)' },
    { value: 'Comuna 11 (Villa General Mitre, Villa Devoto, Villa del Pino, Villa Santa Rita)', label: 'Comuna 11 (Villa General Mitre, Villa Devoto, Villa del Pino, Villa Santa Rita)' },
    { value: 'Comuna 12 (Coghlan, Saavedra, Villa Urquiza, Villa Pueyrredón)', label: 'Comuna 12 (Coghlan, Saavedra, Villa Urquiza, Villa Pueyrredón)' },
    { value: 'Comuna 13 (Núñez, Belgrano, Colegiales)', label: 'Comuna 13 (Núñez, Belgrano, Colegiales)' },
    { value: 'Comuna 14 (Palermo)', label: 'Comuna 14 (Palermo)' },
    { value: 'Comuna 15 (Chacarita, Villa Crespo, La Paternal, Villa Ortúzar, Agronomía, Parque Chas)', label: 'Comuna 15 (Chacarita, Villa Crespo, La Paternal, Villa Ortúzar, Agronomía, Parque Chas)' }
  ]
};

export const ciudadesPorProvincia: { [key: string]: SelectOption[] } = {
  'Buenos Aires': [
    { value: 'La Plata', label: 'La Plata' },
    { value: 'Mar del Plata', label: 'Mar del Plata' },
    { value: 'Bahía Blanca', label: 'Bahía Blanca' },
    { value: 'Tandil', label: 'Tandil' },
    { value: 'Olavarría', label: 'Olavarría' },
    { value: 'Junín', label: 'Junín' },
    { value: 'San Nicolás', label: 'San Nicolás' },
    { value: 'Zárate', label: 'Zárate' },
    { value: 'Quilmes', label: 'Quilmes' },
    { value: 'Lanús', label: 'Lanús' },
    { value: 'Morón', label: 'Morón' },
    { value: 'San Isidro', label: 'San Isidro' },
    { value: 'Tigre', label: 'Tigre' },
    { value: 'Pergamino', label: 'Pergamino' },
    { value: 'Azul', label: 'Azul' },
    { value: 'Mercedes', label: 'Mercedes' },
    { value: 'Luján', label: 'Luján' },
    { value: 'Berisso', label: 'Berisso' },
    { value: 'Ensenada', label: 'Ensenada' },
    { value: 'Tres Arroyos', label: 'Tres Arroyos' },
    { value: 'Dolores', label: 'Dolores' },
    { value: 'Chascomús', label: 'Chascomús' },
    { value: 'San Pedro', label: 'San Pedro' },
    { value: 'Campana', label: 'Campana' },
    { value: 'Chivilcoy', label: 'Chivilcoy' },
    { value: 'Bragado', label: 'Bragado' },
    { value: 'Carlos Casares', label: 'Carlos Casares' },
    { value: 'Balcarce', label: 'Balcarce' },
    { value: 'General Madariaga', label: 'General Madariaga' },
    { value: 'Villa Gesell', label: 'Villa Gesell' },
    { value: 'Pinamar', label: 'Pinamar' },
    { value: 'Necochea', label: 'Necochea' },
    { value: 'Benito Juárez', label: 'Benito Juárez' },
    { value: 'Laprida', label: 'Laprida' },
    { value: 'Pehuajó', label: 'Pehuajó' },
    { value: 'Trenque Lauquen', label: 'Trenque Lauquen' },
    { value: 'General Villegas', label: 'General Villegas' },
    { value: 'Lincoln', label: 'Lincoln' },
    { value: 'General Pinto', label: 'General Pinto' },
    { value: 'Rojas', label: 'Rojas' },
    { value: 'Alberti', label: 'Alberti' },
    { value: 'Navarro', label: 'Navarro' },
    { value: 'Lobos', label: 'Lobos' },
    { value: 'Roque Pérez', label: 'Roque Pérez' },
    { value: 'Saladillo', label: 'Saladillo' },
    { value: 'Bolívar', label: 'Bolívar' },
    { value: 'Daireaux', label: 'Daireaux' },
    { value: 'Henderson', label: 'Henderson' },
    { value: 'Hipólito Yrigoyen', label: 'Hipólito Yrigoyen' }
  ],
  'Catamarca': [
    { value: 'San Fernando del Valle de Catamarca', label: 'San Fernando del Valle de Catamarca' },
    { value: 'Belén', label: 'Belén' },
    { value: 'Tinogasta', label: 'Tinogasta' },
    { value: 'Santa María', label: 'Santa María' },
    { value: 'Recreo', label: 'Recreo' },
    { value: 'Valle Viejo', label: 'Valle Viejo' },
    { value: 'Fray Mamerto Esquiú', label: 'Fray Mamerto Esquiú' },
    { value: 'Andalgalá', label: 'Andalgalá' },
    { value: 'Londres', label: 'Londres' },
    { value: 'Pomán', label: 'Pomán' },
    { value: 'Antofagasta de la Sierra', label: 'Antofagasta de la Sierra' },
    { value: 'El Alto', label: 'El Alto' },
    { value: 'Icaño', label: 'Icaño' },
    { value: 'La Paz', label: 'La Paz' },
    { value: 'Capayán', label: 'Capayán' },
    { value: 'Paclín', label: 'Paclín' }
  ],
  'Chaco': [
    { value: 'Resistencia', label: 'Resistencia' },
    { value: 'Barranqueras', label: 'Barranqueras' },
    { value: 'Presidencia Roque Sáenz Peña', label: 'Presidencia Roque Sáenz Peña' },
    { value: 'Villa Ángela', label: 'Villa Ángela' },
    { value: 'Charata', label: 'Charata' },
    { value: 'Quitilipi', label: 'Quitilipi' },
    { value: 'Machagai', label: 'Machagai' },
    { value: 'Juan José Castelli', label: 'Juan José Castelli' },
    { value: 'Villa Berthet', label: 'Villa Berthet' },
    { value: 'General José de San Martín', label: 'General José de San Martín' },
    { value: 'Tres Isletas', label: 'Tres Isletas' },
    { value: 'Pampa del Infierno', label: 'Pampa del Infierno' },
    { value: 'Nueva Pompeya', label: 'Nueva Pompeya' }
  ],
  'Chubut': [
    { value: 'Rawson', label: 'Rawson' },
    { value: 'Comodoro Rivadavia', label: 'Comodoro Rivadavia' },
    { value: 'Puerto Madryn', label: 'Puerto Madryn' },
    { value: 'Trelew', label: 'Trelew' },
    { value: 'Esquel', label: 'Esquel' },
    { value: 'El Maitén', label: 'El Maitén' },
    { value: 'Cushamen', label: 'Cushamen' },
    { value: 'Gaiman', label: 'Gaiman' },
    { value: 'Dolavon', label: 'Dolavon' },
    { value: '28 de Julio', label: '28 de Julio' }
  ],
  'Córdoba': [
    { value: 'Córdoba', label: 'Córdoba' },
    { value: 'Villa María', label: 'Villa María' },
    { value: 'Río Cuarto', label: 'Río Cuarto' },
    { value: 'San Francisco', label: 'San Francisco' },
    { value: 'Villa Carlos Paz', label: 'Villa Carlos Paz' },
    { value: 'Jesús María', label: 'Jesús María' },
    { value: 'La Falda', label: 'La Falda' },
    { value: 'Bell Ville', label: 'Bell Ville' },
    { value: 'Río Segundo', label: 'Río Segundo' },
    { value: 'Alta Gracia', label: 'Alta Gracia' },
    { value: 'Villa Dolores', label: 'Villa Dolores' },
    { value: 'Mina Clavero', label: 'Mina Clavero' },
    { value: 'Cosquín', label: 'Cosquín' },
    { value: 'Santa Rosa de Calamuchita', label: 'Santa Rosa de Calamuchita' },
    { value: 'Deán Funes', label: 'Deán Funes' }
  ],
  'Corrientes': [
    { value: 'Corrientes', label: 'Corrientes' },
    { value: 'Goya', label: 'Goya' },
    { value: 'Passo de los Libres', label: 'Passo de los Libres' },
    { value: 'Santo Tomé', label: 'Santo Tomé' },
    { value: 'Monte Caseros', label: 'Monte Caseros' },
    { value: 'Curuzú Cuatiá', label: 'Curuzú Cuatiá' },
    { value: 'Concepción', label: 'Concepción' },
    { value: 'Bella Vista', label: 'Bella Vista' },
    { value: 'Ituzaingó', label: 'Ituzaingó' },
    { value: 'Empedrado', label: 'Empedrado' },
    { value: 'Saladas', label: 'Saladas' },
    { value: 'San Roque', label: 'San Roque' },
    { value: 'Paysandú', label: 'Paysandú' }
  ],
  'Entre Ríos': [
    { value: 'Paraná', label: 'Paraná' },
    { value: 'Concordia', label: 'Concordia' },
    { value: 'Gualeguaychú', label: 'Gualeguaychú' },
    { value: 'Concepción del Uruguay', label: 'Concepción del Uruguay' },
    { value: 'Gualeguay', label: 'Gualeguay' },
    { value: 'Victoria', label: 'Victoria' },
    { value: 'Chajarí', label: 'Chajarí' },
    { value: 'Federación', label: 'Federación' },
    { value: 'Villaguay', label: 'Villaguay' },
    { value: 'Colón', label: 'Colón' },
    { value: 'Nogoyá', label: 'Nogoyá' },
    { value: 'Crespo', label: 'Crespo' },
    { value: 'Diamante', label: 'Diamante' },
    { value: 'Uruguay', label: 'Uruguay' }
  ],
  'Formosa': [
    { value: 'Formosa', label: 'Formosa' },
    { value: 'Clorinda', label: 'Clorinda' },
    { value: 'Ibarra', label: 'Ibarra' },
    { value: 'Pirané', label: 'Pirané' },
    { value: 'El Colorado', label: 'El Colorado' },
    { value: 'Las Lomitas', label: 'Las Lomitas' },
    { value: 'General Mosconi', label: 'General Mosconi' },
    { value: 'Bartolomé de las Casas', label: 'Bartolomé de las Casas' },
    { value: 'Alto del Carmen', label: 'Alto del Carmen' }
  ],
  'Jujuy': [
    { value: 'San Salvador de Jujuy', label: 'San Salvador de Jujuy' },
    { value: 'Palpalá', label: 'Palpalá' },
    { value: 'Libertador General San Martín', label: 'Libertador General San Martín' },
    { value: 'Perico', label: 'Perico' },
    { value: 'El Carmen', label: 'El Carmen' },
    { value: 'San Pedro', label: 'San Pedro' },
    { value: 'La Quiaca', label: 'La Quiaca' },
    { value: 'Humahuaca', label: 'Humahuaca' },
    { value: 'Tilcara', label: 'Tilcara' },
    { value: 'Yavi', label: 'Yavi' },
    { value: 'Santa Catalina', label: 'Santa Catalina' },
    { value: 'Abra Pampa', label: 'Abra Pampa' },
    { value: 'Caimancito', label: 'Caimancito' },
    { value: 'Susques', label: 'Susques' }
  ],
  'La Pampa': [
    { value: 'Santa Rosa', label: 'Santa Rosa' },
    { value: 'General Pico', label: 'General Pico' },
    { value: 'Toay', label: 'Toay' },
    { value: 'Realicó', label: 'Realicó' },
    { value: 'Intendente Alvear', label: 'Intendente Alvear' },
    { value: 'Quemú Quemú', label: 'Quemú Quemú' },
    { value: 'Rancul', label: 'Rancul' },
    { value: 'General Acha', label: 'General Acha' },
    { value: 'Ceballos', label: 'Ceballos' },
    { value: 'Speluzzi', label: 'Speluzzi' },
    { value: 'Dorila', label: 'Dorila' },
    { value: 'Winifreda', label: 'Winifreda' }
  ],
  'La Rioja': [
    { value: 'La Rioja', label: 'La Rioja' },
    { value: 'Chilecito', label: 'Chilecito' },
    { value: 'Aimogasta', label: 'Aimogasta' },
    { value: 'Vinchina', label: 'Vinchina' },
    { value: 'Famatina', label: 'Famatina' },
    { value: 'Nonogasta', label: 'Nonogasta' },
    { value: 'San Blas de los Sauces', label: 'San Blas de los Sauces' },
    { value: 'Chepes', label: 'Chepes' },
    { value: 'Villa Castelli', label: 'Villa Castelli' },
    { value: 'Santa Rita', label: 'Santa Rita' }
  ],
  'Mendoza': [
    { value: 'Mendoza', label: 'Mendoza' },
    { value: 'Godoy Cruz', label: 'Godoy Cruz' },
    { value: 'Las Heras', label: 'Las Heras' },
    { value: 'San Martín', label: 'San Martín' },
    { value: 'Guaymallén', label: 'Guaymallén' },
    { value: 'Luján de Cuyo', label: 'Luján de Cuyo' },
    { value: 'Maipú', label: 'Maipú' },
    { value: 'San Rafael', label: 'San Rafael' },
    { value: 'Malargüe', label: 'Malargüe' },
    { value: 'Tunuyán', label: 'Tunuyán' },
    { value: 'Tupungato', label: 'Tupungato' },
    { value: 'General Alvear', label: 'General Alvear' },
    { value: 'Rivadavia', label: 'Rivadavia' },
    { value: 'San Carlos', label: 'San Carlos' },
    { value: 'Santa Rosa', label: 'Santa Rosa' },
    { value: 'La Paz', label: 'La Paz' }
  ],
  'Misiones': [
    { value: 'Posadas', label: 'Posadas' },
    { value: 'Puerto Iguazú', label: 'Puerto Iguazú' },
    { value: 'Eldorado', label: 'Eldorado' },
    { value: 'Apóstoles', label: 'Apóstoles' },
    { value: 'Corrientes', label: 'Corrientes' },
    { value: 'Montecarlo', label: 'Montecarlo' },
    { value: 'Puerto Rico', label: 'Puerto Rico' },
    { value: 'Oberá', label: 'Oberá' },
    { value: 'San Pedro', label: 'San Pedro' },
    { value: 'Leandro N. Alem', label: 'Leandro N. Alem' },
    { value: 'Jardín América', label: 'Jardín América' },
    { value: 'Campo Ramón', label: 'Campo Ramón' },
    { value: 'Campo Viera', label: 'Campo Viera' },
    { value: 'Garupá', label: 'Garupá' }
  ],
  'Neuquén': [
    { value: 'Neuquén', label: 'Neuquén' },
    { value: 'Cipolletti', label: 'Cipolletti' },
    { value: 'Plottier', label: 'Plottier' },
    { value: 'Zapala', label: 'Zapala' },
    { value: 'Aluminé', label: 'Aluminé' },
    { value: 'Chos Malal', label: 'Chos Malal' },
    { value: 'Caviahue-Copahue', label: 'Caviahue-Copahue' },
    { value: 'Loncopué', label: 'Loncopué' },
    { value: 'San Martín de los Andes', label: 'San Martín de los Andes' },
    { value: 'Villa La Angostura', label: 'Villa La Angostura' },
    { value: 'Junín de los Andes', label: 'Junín de los Andes' },
    { value: 'Centenario', label: 'Centenario' },
    { value: 'Río Colorado', label: 'Río Colorado' },
    { value: 'Villa Pehuenia', label: 'Villa Pehuenia' }
  ],
  'Río Negro': [
    { value: 'Viedma', label: 'Viedma' },
    { value: 'Bariloche', label: 'Bariloche' },
    { value: 'General Roca', label: 'General Roca' },
    { value: 'Cipolletti', label: 'Cipolletti' },
    { value: 'Allen', label: 'Allen' },
    { value: 'San Carlos de Bariloche', label: 'San Carlos de Bariloche' },
    { value: 'El Bolsón', label: 'El Bolsón' },
    { value: 'Cinco Saltos', label: 'Cinco Saltos' },
    { value: 'Río Colorado', label: 'Río Colorado' },
    { value: 'Choele Choel', label: 'Choele Choel' },
    { value: 'Luis Beltrán', label: 'Luis Beltrán' },
    { value: 'General Conesa', label: 'General Conesa' },
    { value: 'Guardia Mitre', label: 'Guardia Mitre' },
    { value: 'Valcheta', label: 'Valcheta' }
  ],
  'Salta': [
    { value: 'Salta', label: 'Salta' },
    { value: 'San Ramón de la Nueva Orán', label: 'San Ramón de la Nueva Orán' },
    { value: 'Tartagal', label: 'Tartagal' },
    { value: 'Embarcación', label: 'Embarcación' },
    { value: 'Jujuy', label: 'Jujuy' },
    { value: 'Rosario de la Frontera', label: 'Rosario de la Frontera' },
    { value: 'Cafayate', label: 'Cafayate' },
    { value: 'Cachi', label: 'Cachi' },
    { value: 'Molinos', label: 'Molinos' },
    { value: 'San Antonio de los Cobres', label: 'San Antonio de los Cobres' },
    { value: 'Iruya', label: 'Iruya' },
    { value: 'Santa Rosa de Tastil', label: 'Santa Rosa de Tastil' },
    { value: 'Campo Quijano', label: 'Campo Quijano' },
    { value: 'La Caldera', label: 'La Caldera' }
  ],
  'San Juan': [
    { value: 'San Juan', label: 'San Juan' },
    { value: 'Rawson', label: 'Rawson' },
    { value: 'Chimbas', label: 'Chimbas' },
    { value: 'Santa Lucia', label: 'Santa Lucia' },
    { value: 'Pocito', label: 'Pocito' },
    { value: 'Caucete', label: 'Caucete' },
    { value: 'Albardón', label: 'Albardón' },
    { value: 'Calingasta', label: 'Calingasta' },
    { value: 'Jáchal', label: 'Jáchal' },
    { value: 'Iglesia', label: 'Iglesia' },
    { value: 'Rivadavia', label: 'Rivadavia' },
    { value: 'San Martín', label: 'San Martín' },
    { value: 'Ullum', label: 'Ullum' },
    { value: 'Valle Fértil', label: 'Valle Fértil' },
    { value: 'Zonda', label: 'Zonda' }
  ],
  'San Luis': [
    { value: 'San Luis', label: 'San Luis' },
    { value: 'Villa Mercedes', label: 'Villa Mercedes' },
    { value: 'Merlo', label: 'Merlo' },
    { value: 'Concarán', label: 'Concarán' },
    { value: 'Juárez Celman', label: 'Juárez Celman' },
    { value: 'Quines', label: 'Quines' },
    { value: 'Naschel', label: 'Naschel' },
    { value: 'La Toma', label: 'La Toma' },
    { value: 'Potrero de los Funes', label: 'Potrero de los Funes' },
    { value: 'El Morro', label: 'El Morro' },
    { value: 'San Francisco del Monte de Oro', label: 'San Francisco del Monte de Oro' },
    { value: 'San José del Morro', label: 'San José del Morro' }
  ],
  'Santa Cruz': [
    { value: 'Río Gallegos', label: 'Río Gallegos' },
    { value: 'Caleta Olivia', label: 'Caleta Olivia' },
    { value: 'Puerto Deseado', label: 'Puerto Deseado' },
    { value: 'El Calafate', label: 'El Calafate' },
    { value: 'Pico Truncado', label: 'Pico Truncado' },
    { value: 'Las Heras', label: 'Las Heras' },
    { value: 'Gobernador Gregores', label: 'Gobernador Gregores' },
    { value: 'Los Antiguos', label: 'Los Antiguos' },
    { value: 'Tres Lagos', label: 'Tres Lagos' }
  ],
  'Santa Fe': [
    { value: 'Santa Fe', label: 'Santa Fe' },
    { value: 'Rosario', label: 'Rosario' },
    { value: 'San Lorenzo', label: 'San Lorenzo' },
    { value: 'Rafaela', label: 'Rafaela' },
    { value: 'Villa Gobernador Gálvez', label: 'Villa Gobernador Gálvez' },
    { value: 'Venado Tuerto', label: 'Venado Tuerto' },
    { value: 'Reconquista', label: 'Reconquista' },
    { value: 'Santo Tomé', label: 'Santo Tomé' },
    { value: 'Esperanza', label: 'Esperanza' },
    { value: 'San Carlos', label: 'San Carlos' },
    { value: 'Funes', label: 'Funes' },
    { value: 'Pérez', label: 'Pérez' },
    { value: 'Sunchales', label: 'Sunchales' },
    { value: 'San Jorge', label: 'San Jorge' },
    { value: 'Cayastá', label: 'Cayastá' }
  ],
  'Santiago del Estero': [
    { value: 'Santiago del Estero', label: 'Santiago del Estero' },
    { value: 'La Banda', label: 'La Banda' },
    { value: 'Fray Mamerto Esquiú', label: 'Fray Mamerto Esquiú' },
    { value: 'Añatuya', label: 'Añatuya' },
    { value: 'Termas de Río Hondo', label: 'Termas de Río Hondo' },
    { value: 'Bandera', label: 'Bandera' },
    { value: 'Clodomira', label: 'Clodomira' },
    { value: 'Santo Tomé', label: 'Santo Tomé' },
    { value: 'Villa Ojo de Agua', label: 'Villa Ojo de Agua' },
    { value: 'Quimilí', label: 'Quimilí' },
    { value: 'Alto del Carmen', label: 'Alto del Carmen' },
    { value: 'San Pedro', label: 'San Pedro' },
    { value: 'Los Toldos', label: 'Los Toldos' },
    { value: 'Monte Quemado', label: 'Monte Quemado' }
  ],
  'Tierra del Fuego': [
    { value: 'Ushuaia', label: 'Ushuaia' },
    { value: 'Río Grande', label: 'Río Grande' },
    { value: 'Tolhuin', label: 'Tolhuin' }
  ],
  'Tucumán': [
    { value: 'San Miguel de Tucumán', label: 'San Miguel de Tucumán' },
    { value: 'Yerba Buena', label: 'Yerba Buena' },
    { value: 'Concepción', label: 'Concepción' },
    { value: 'Famaillá', label: 'Famaillá' },
    { value: 'Aguilares', label: 'Aguilares' },
    { value: 'Banda del Río Salí', label: 'Banda del Río Salí' },
    { value: 'San Fernando del Valle de Catamarca', label: 'San Fernando del Valle de Catamarca' },
    { value: 'Tafí Viejo', label: 'Tafí Viejo' },
    { value: 'Monteros', label: 'Monteros' },
    { value: 'Lules', label: 'Lules' },
    { value: 'Alberdi', label: 'Alberdi' },
    { value: 'Aguas de Soto', label: 'Aguas de Soto' },
    { value: 'Los Naranjos', label: 'Los Naranjos' },
    { value: 'Yánima', label: 'Yánima' }
  ],
  'Ciudad Autónoma de Buenos Aires': [
    { value: 'Buenos Aires', label: 'Buenos Aires' }
  ]
};
